function execute() {
    return Response.success([
        {title: "3D Hentai", input: "https://hentaivn.tv/the-loai-3-3d_hentai.html", script: "gen.js"},
        {title: "Action", input: "https://hentaivn.tv/the-loai-5-action.html", script: "gen.js"},
        {title: "Adult", input: "https://hentaivn.tv/the-loai-116-adult.html", script: "gen.js"},
        {title: "Adventure", input: "https://hentaivn.tv/the-loai-203-adventure.html", script: "gen.js"},
        {title: "Ahegao", input: "https://hentaivn.tv/the-loai-20-ahegao.html", script: "gen.js"},
        {title: "Anal", input: "https://hentaivn.tv/the-loai-21-anal.html", script: "gen.js"},
        {title: "Angel", input: "https://hentaivn.tv/the-loai-249-angel.html", script: "gen.js"},
        {title: "Ảnh động", input: "https://hentaivn.tv/the-loai-131-anh_dong.html", script: "gen.js"},
        {title: "Animal", input: "https://hentaivn.tv/the-loai-127-animal.html", script: "gen.js"},
        {title: "Animal girl", input: "https://hentaivn.tv/the-loai-22-animal_girl.html", script: "gen.js"},
        {title: "Artist CG", input: "https://hentaivn.tv/the-loai-115-artist.html", script: "gen.js"},
        {title: "BBM", input: "https://hentaivn.tv/the-loai-257-bbm.html", script: "gen.js"},
        {title: "BBW", input: "https://hentaivn.tv/the-loai-251-bbw.html", script: "gen.js"},
        {title: "BDSM", input: "https://hentaivn.tv/the-loai-24-bdsm.html", script: "gen.js"},
        {title: "Bestiality", input: "https://hentaivn.tv/the-loai-25-bestiality.html", script: "gen.js"},
        {title: "Big Ass", input: "https://hentaivn.tv/the-loai-133-big_ass.html", script: "gen.js"},
        {title: "Big Boobs", input: "https://hentaivn.tv/the-loai-23-big_boobs.html", script: "gen.js"},
        {title: "Big Penis", input: "https://hentaivn.tv/the-loai-32-big_penis.html", script: "gen.js"},
        {title: "Blackmail", input: "https://hentaivn.tv/the-loai-267-blackmail.html", script: "gen.js"},
        {title: "Bloomers", input: "https://hentaivn.tv/the-loai-27-bloomers.html", script: "gen.js"},
        {title: "BlowJobs", input: "https://hentaivn.tv/the-loai-28-blowjobs.html", script: "gen.js"},
        {title: "Body Swap", input: "https://hentaivn.tv/the-loai-29-body_swap.html", script: "gen.js"},
        {title: "Bodysuit", input: "https://hentaivn.tv/the-loai-30-bodysuit.html", script: "gen.js"},
        {title: "Bondage", input: "https://hentaivn.tv/the-loai-254-bondage.html", script: "gen.js"},
        {title: "Breast Sucking", input: "https://hentaivn.tv/the-loai-33-breast_sucking.html", script: "gen.js"},
        {title: "BreastJobs", input: "https://hentaivn.tv/the-loai-248-boob-jobs.html", script: "gen.js"},
        {title: "Brocon", input: "https://hentaivn.tv/the-loai-31-brocon.html", script: "gen.js"},
        {title: "Brother", input: "https://hentaivn.tv/the-loai-242-brother.html", script: "gen.js"},
        {title: "Business Suit", input: "https://hentaivn.tv/the-loai-241-business-suit.html", script: "gen.js"},
        {title: "Catgirls", input: "https://hentaivn.tv/the-loai-39-catgirls.html", script: "gen.js"},
        {title: "Che ít", input: "https://hentaivn.tv/the-loai-101-che_it.html", script: "gen.js"},
        {title: "Che nhiều", input: "https://hentaivn.tv/the-loai-129-che_nhieu.html", script: "gen.js"},
        {title: "Cheating", input: "https://hentaivn.tv/the-loai-34-cheating.html", script: "gen.js"},
        {title: "Chikan", input: "https://hentaivn.tv/the-loai-35-chikan.html", script: "gen.js"},
        {title: "Chinese Dress", input: "https://hentaivn.tv/the-loai-271-chinese-dress.html", script: "gen.js"},
        {title: "Có che", input: "https://hentaivn.tv/the-loai-100-co_che.html", script: "gen.js"},
        {title: "Comedy", input: "https://hentaivn.tv/the-loai-36-comedy.html", script: "gen.js"},
        {title: "Comic", input: "https://hentaivn.tv/the-loai-120-comic.html", script: "gen.js"},
        {title: "Condom", input: "https://hentaivn.tv/the-loai-210-condom.html", script: "gen.js"},
        {title: "Cosplay", input: "https://hentaivn.tv/the-loai-38-cosplay.html", script: "gen.js"},
        {title: "Cousin", input: "https://hentaivn.tv/the-loai-2-cousin.html", script: "gen.js"},
        {title: "Cunnilingus", input: "https://hentaivn.tv/the-loai-269-cunnilingus.html", script: "gen.js"},
        {title: "Dark Skin", input: "https://hentaivn.tv/the-loai-40-dark_skin.html", script: "gen.js"},
        {title: "Daughter", input: "https://hentaivn.tv/the-loai-262-daughter.html", script: "gen.js"},
        {title: "Deepthroat", input: "https://hentaivn.tv/the-loai-268-deepthroat.html", script: "gen.js"},
        {title: "Demon", input: "https://hentaivn.tv/the-loai-132-demon.html", script: "gen.js"},
        {title: "DemonGirl", input: "https://hentaivn.tv/the-loai-212-demon-girl.html", script: "gen.js"},
        {title: "Devil", input: "https://hentaivn.tv/the-loai-104-devil.html", script: "gen.js"},
        {title: "DevilGirl", input: "https://hentaivn.tv/the-loai-105-devilgirl.html", script: "gen.js"},
        {title: "Dirty", input: "https://hentaivn.tv/the-loai-253-dirty.html", script: "gen.js"},
        {title: "Dirty Old Man", input: "https://hentaivn.tv/the-loai-41-dirty_old_man.html", script: "gen.js"},
        {title: "DogGirl", input: "https://hentaivn.tv/the-loai-260-doggirl.html", script: "gen.js"},
        {title: "Double Penetration", input: "https://hentaivn.tv/the-loai-42-double_penetration.html", script: "gen.js"},
        {title: "Doujinshi", input: "https://hentaivn.tv/the-loai-44-doujinshi.html", script: "gen.js"},
        {title: "Drama", input: "https://hentaivn.tv/the-loai-4-drama.html", script: "gen.js"},
        {title: "Drug", input: "https://hentaivn.tv/the-loai-43-drug.html", script: "gen.js"},
        {title: "Ecchi", input: "https://hentaivn.tv/the-loai-45-ecchi.html", script: "gen.js"},
        {title: "Elder Sister", input: "https://hentaivn.tv/the-loai-245-elder-sister.html", script: "gen.js"},
        {title: "Elf", input: "https://hentaivn.tv/the-loai-125-elf.html", script: "gen.js"},
        {title: "Exhibitionism", input: "https://hentaivn.tv/the-loai-46-exhibitionism.html", script: "gen.js"},
        {title: "Fantasy", input: "https://hentaivn.tv/the-loai-123-fantasy.html", script: "gen.js"},
        {title: "Father", input: "https://hentaivn.tv/the-loai-243-father.html", script: "gen.js"},
        {title: "Femdom", input: "https://hentaivn.tv/the-loai-47-femdom.html", script: "gen.js"},
        {title: "Fingering", input: "https://hentaivn.tv/the-loai-48-fingering.html", script: "gen.js"},
        {title: "Footjob", input: "https://hentaivn.tv/the-loai-108-footjob.html", script: "gen.js"},
        {title: "Foxgirls", input: "https://hentaivn.tv/the-loai-259-foxgirl.html", script: "gen.js"},
        {title: "Full Color", input: "https://hentaivn.tv/the-loai-37-full_color.html", script: "gen.js"},
        {title: "Furry", input: "https://hentaivn.tv/the-loai-202-furry.html", script: "gen.js"},
        {title: "Futanari", input: "https://hentaivn.tv/the-loai-50-futanari.html", script: "gen.js"},
        {title: "Game", input: "https://hentaivn.tv/the-loai-130-game.html", script: "gen.js"},
        {title: "GangBang", input: "https://hentaivn.tv/the-loai-51-gangbang.html", script: "gen.js"},
        {title: "Garter Belts", input: "https://hentaivn.tv/the-loai-206-garter_belts.html", script: "gen.js"},
        {title: "Gender Bender", input: "https://hentaivn.tv/the-loai-52-gender_bender.html", script: "gen.js"},
        {title: "Ghost", input: "https://hentaivn.tv/the-loai-106-ghost.html", script: "gen.js"},
        {title: "Glasses", input: "https://hentaivn.tv/the-loai-56-glasses.html", script: "gen.js"},
        {title: "Gothic Lolita", input: "https://hentaivn.tv/the-loai-264-gothic-lolita.html", script: "gen.js"},
        {title: "Group", input: "https://hentaivn.tv/the-loai-53-group.html", script: "gen.js"},
        {title: "Guro", input: "https://hentaivn.tv/the-loai-55-guro.html", script: "gen.js"},
        {title: "Hairy", input: "https://hentaivn.tv/the-loai-247-hairy.html", script: "gen.js"},
        {title: "Handjob", input: "https://hentaivn.tv/the-loai-57-handjob.html", script: "gen.js"},
        {title: "Harem", input: "https://hentaivn.tv/the-loai-58-harem.html", script: "gen.js"},
        {title: "HentaiVN", input: "https://hentaivn.tv/the-loai-102-hentaivn.html", script: "gen.js"},
        {title: "Historical", input: "https://hentaivn.tv/the-loai-80-historical.html", script: "gen.js"},
        {title: "Horror", input: "https://hentaivn.tv/the-loai-122-horror.html", script: "gen.js"},
        {title: "Housewife", input: "https://hentaivn.tv/the-loai-59-housewife.html", script: "gen.js"},
        {title: "Humiliation", input: "https://hentaivn.tv/the-loai-60-humiliation.html", script: "gen.js"},
        {title: "Idol", input: "https://hentaivn.tv/the-loai-61-idol.html", script: "gen.js"},
        {title: "Imouto", input: "https://hentaivn.tv/the-loai-244-imouto.html", script: "gen.js"},
        {title: "Incest", input: "https://hentaivn.tv/the-loai-62-incest.html", script: "gen.js"},
        {title: "Insect (Côn Trùng)", input: "https://hentaivn.tv/the-loai-26-insect.html", script: "gen.js"},
        {title: "Không che", input: "https://hentaivn.tv/the-loai-99-khong_che.html", script: "gen.js"},
        {title: "Kimono", input: "https://hentaivn.tv/the-loai-110-kimono.html", script: "gen.js"},
        {title: "Kuudere", input: "https://hentaivn.tv/the-loai-265-kuudere.html", script: "gen.js"},
        {title: "Loli", input: "https://hentaivn.tv/the-loai-63-loli.html", script: "gen.js"},
        {title: "Maids", input: "https://hentaivn.tv/the-loai-64-maids.html", script: "gen.js"},
        {title: "Manhwa", input: "https://hentaivn.tv/the-loai-114-manhwa.html", script: "gen.js"},
        {title: "Masturbation", input: "https://hentaivn.tv/the-loai-65-tu_suong.html", script: "gen.js"},
        {title: "Mature", input: "https://hentaivn.tv/the-loai-119-mature.html", script: "gen.js"},
        {title: "Miko", input: "https://hentaivn.tv/the-loai-124-miko.html", script: "gen.js"},
        {title: "Milf", input: "https://hentaivn.tv/the-loai-126-milf.html", script: "gen.js"},
        {title: "Mind Break", input: "https://hentaivn.tv/the-loai-121-mind_break.html", script: "gen.js"},
        {title: "Mind Control", input: "https://hentaivn.tv/the-loai-113-mind_control.html", script: "gen.js"},
        {title: "Mizugi", input: "https://hentaivn.tv/the-loai-263-mizugi.html", script: "gen.js"},
        {title: "Monster", input: "https://hentaivn.tv/the-loai-66-monster.html", script: "gen.js"},
        {title: "Monstergirl", input: "https://hentaivn.tv/the-loai-67-monstergirl.html", script: "gen.js"},
        {title: "Mother", input: "https://hentaivn.tv/the-loai-103-mother.html", script: "gen.js"},
        {title: "Nakadashi", input: "https://hentaivn.tv/the-loai-205-nakadashi.html", script: "gen.js"},
        {title: "Netori", input: "https://hentaivn.tv/the-loai-1-netori.html", script: "gen.js"},
        {title: "Non-hen", input: "https://hentaivn.tv/the-loai-201-non_hen.html", script: "gen.js"},
        {title: "NTR", input: "https://hentaivn.tv/the-loai-68-ntr.html", script: "gen.js"},
        {title: "Nun", input: "https://hentaivn.tv/the-loai-272-nun.html", script: "gen.js"},
        {title: "Nurse", input: "https://hentaivn.tv/the-loai-69-nurse.html", script: "gen.js"},
        {title: "Old Man", input: "https://hentaivn.tv/the-loai-211-old-man.html", script: "gen.js"},
        {title: "Oneshot", input: "https://hentaivn.tv/the-loai-71-oneshot.html", script: "gen.js"},
        {title: "Oral", input: "https://hentaivn.tv/the-loai-70-oral.html", script: "gen.js"},
        {title: "Osananajimi", input: "https://hentaivn.tv/the-loai-209-osananajimi.html", script: "gen.js"},
        {title: "Paizuri", input: "https://hentaivn.tv/the-loai-72-paizuri.html", script: "gen.js"},
        {title: "Pantyhose", input: "https://hentaivn.tv/the-loai-204-pantyhose.html", script: "gen.js"},
        {title: "Pregnant", input: "https://hentaivn.tv/the-loai-73-pregnant.html", script: "gen.js"},
        {title: "Rape", input: "https://hentaivn.tv/the-loai-98-rape.html", script: "gen.js"},
        {title: "Rimjob", input: "https://hentaivn.tv/the-loai-258-rimjob.html", script: "gen.js"},
        {title: "Romance", input: "https://hentaivn.tv/the-loai-117-romance.html", script: "gen.js"},
        {title: "Ryona", input: "https://hentaivn.tv/the-loai-207-ryona.html", script: "gen.js"},
        {title: "Scat", input: "https://hentaivn.tv/the-loai-134-scat.html", script: "gen.js"},
        {title: "School Uniform", input: "https://hentaivn.tv/the-loai-74-school_uniform.html", script: "gen.js"},
        {title: "SchoolGirl", input: "https://hentaivn.tv/the-loai-75-schoolgirl.html", script: "gen.js"},
        {title: "Series", input: "https://hentaivn.tv/the-loai-87-series.html", script: "gen.js"},
        {title: "Sex Toys", input: "https://hentaivn.tv/the-loai-88-sex_toys.html", script: "gen.js"},
        {title: "Shimapan", input: "https://hentaivn.tv/the-loai-246-shimapan.html", script: "gen.js"},
        {title: "Short Hentai", input: "https://hentaivn.tv/the-loai-118-short_hentai.html", script: "gen.js"},
        {title: "Shota", input: "https://hentaivn.tv/the-loai-77-shota.html", script: "gen.js"},
        {title: "Shoujo", input: "https://hentaivn.tv/the-loai-76-shoujo.html", script: "gen.js"},
        {title: "Siscon", input: "https://hentaivn.tv/the-loai-79-siscon.html", script: "gen.js"},
        {title: "Sister", input: "https://hentaivn.tv/the-loai-78-sister.html", script: "gen.js"},
        {title: "Slave", input: "https://hentaivn.tv/the-loai-82-slave.html", script: "gen.js"},
        {title: "Sleeping", input: "https://hentaivn.tv/the-loai-213-sleeping.html", script: "gen.js"},
        {title: "Small Boobs", input: "https://hentaivn.tv/the-loai-84-small_boobs.html", script: "gen.js"},
        {title: "Sports", input: "https://hentaivn.tv/the-loai-83-sports.html", script: "gen.js"},
        {title: "Stockings", input: "https://hentaivn.tv/the-loai-81-stockings.html", script: "gen.js"},
        {title: "Supernatural", input: "https://hentaivn.tv/the-loai-85-supernatural.html", script: "gen.js"},
        {title: "Sweating", input: "https://hentaivn.tv/the-loai-250-sweatin.html", script: "gen.js"},
        {title: "Swimsuit", input: "https://hentaivn.tv/the-loai-86-swimsuit.html", script: "gen.js"},
        {title: "Tall Girl", input: "https://hentaivn.tv/the-loai-266-tall-girls.html", script: "gen.js"},
        {title: "Teacher", input: "https://hentaivn.tv/the-loai-91-teacher.html", script: "gen.js"},
        {title: "Tentacles", input: "https://hentaivn.tv/the-loai-89-tentacles.html", script: "gen.js"},
        {title: "Time Stop", input: "https://hentaivn.tv/the-loai-109-time_stop.html", script: "gen.js"},
        {title: "Tomboy", input: "https://hentaivn.tv/the-loai-90-tomboy.html", script: "gen.js"},
        {title: "Tracksuit", input: "https://hentaivn.tv/the-loai-252-tracksuit.html", script: "gen.js"},
        {title: "Transformation", input: "https://hentaivn.tv/the-loai-256-transformation.html", script: "gen.js"},
        {title: "Trap", input: "https://hentaivn.tv/the-loai-92-trap.html", script: "gen.js"},
        {title: "Tsundere", input: "https://hentaivn.tv/the-loai-111-tsundere.html", script: "gen.js"},
        {title: "Twins", input: "https://hentaivn.tv/the-loai-93-twins.html", script: "gen.js"},
        {title: "Twintails", input: "https://hentaivn.tv/the-loai-261-twintails.html", script: "gen.js"},
        {title: "Vampire", input: "https://hentaivn.tv/the-loai-107-vampire.html", script: "gen.js"},
        {title: "Vanilla", input: "https://hentaivn.tv/the-loai-208-vanilla.html", script: "gen.js"},
        {title: "Virgin", input: "https://hentaivn.tv/the-loai-95-virgin.html", script: "gen.js"},
        {title: "Webtoon", input: "https://hentaivn.tv/the-loai-270-webtoon.html", script: "gen.js"},
        {title: "X-ray", input: "https://hentaivn.tv/the-loai-94-x_ray.html", script: "gen.js"},
        {title: "Yandere", input: "https://hentaivn.tv/the-loai-112-yandere.html", script: "gen.js"},
        {title: "Yaoi", input: "https://hentaivn.tv/the-loai-96-yaoi.html", script: "gen.js"},
        {title: "Yuri", input: "https://hentaivn.tv/the-loai-97-yuri.html", script: "gen.js"},
        {title: "Zombie", input: "https://hentaivn.tv/the-loai-128-zombie.html", script: "gen.js"}
    ]);
}