function execute() {
    return Response.success([
        {title: "16+", input: "https://truyenvn.com/the-loai/16", script: "gen.js"},
        {title: "Action", input: "https://truyenvn.com/the-loai/action", script: "gen.js"},
        {title: "Adult", input: "https://truyenvn.com/the-loai/adult", script: "gen.js"},
        {title: "Adventure", input: "https://truyenvn.com/the-loai/adventure", script: "gen.js"},
        {title: "Anime", input: "https://truyenvn.com/the-loai/anime", script: "gen.js"},
        {title: "Chuyển Sinh", input: "https://truyenvn.com/the-loai/chuyen-sinh", script: "gen.js"},
        {title: "Cổ Đại", input: "https://truyenvn.com/the-loai/co-dai", script: "gen.js"},
        {title: "Comedy", input: "https://truyenvn.com/the-loai/comedy", script: "gen.js"},
        {title: "Comic", input: "https://truyenvn.com/the-loai/comic", script: "gen.js"},
        {title: "DC Comic", input: "https://truyenvn.com/the-loai/dc-comic", script: "gen.js"},
        {title: "Demons", input: "https://truyenvn.com/the-loai/demons", script: "gen.js"},
        {title: "Detective", input: "https://truyenvn.com/the-loai/detective", script: "gen.js"},
        {title: "Doujinshi", input: "https://truyenvn.com/the-loai/doujinshi", script: "gen.js"},
        {title: "Drama", input: "https://truyenvn.com/the-loai/drama", script: "gen.js"},
        {title: "Đam Mỹ", input: "https://truyenvn.com/the-loai/dam-my", script: "gen.js"},
        {title: "Ecchi", input: "https://truyenvn.com/the-loai/ecchi", script: "gen.js"},
        {title: "Fantasy", input: "https://truyenvn.com/the-loai/fantasy", script: "gen.js"},
        {title: "Gender Bender", input: "https://truyenvn.com/the-loai/gender-bender", script: "gen.js"},
        {title: "Giang Hồ", input: "https://truyenvn.com/the-loai/giang-ho", script: "gen.js"},
        {title: "Gintama DJ", input: "https://truyenvn.com/the-loai/gintama-dj", script: "gen.js"},
        {title: "Harem", input: "https://truyenvn.com/the-loai/harem", script: "gen.js"},
        {title: "Historical", input: "https://truyenvn.com/the-loai/historical", script: "gen.js"},
        {title: "Horror", input: "https://truyenvn.com/the-loai/horror", script: "gen.js"},
        {title: "Huyền Huyễn", input: "https://truyenvn.com/the-loai/huyen-huyen", script: "gen.js"},
        {title: "Isekai", input: "https://truyenvn.com/the-loai/isekai", script: "gen.js"},
        {title: "Josei", input: "https://truyenvn.com/the-loai/josei", script: "gen.js"},
        {title: "Mafia", input: "https://truyenvn.com/the-loai/mafia", script: "gen.js"},
        {title: "Magic", input: "https://truyenvn.com/the-loai/magic", script: "gen.js"},
        {title: "Manga", input: "https://truyenvn.com/the-loai/manga", script: "gen.js"},
        {title: "Manhua", input: "https://truyenvn.com/the-loai/manhua", script: "gen.js"},
        {title: "Manhwa", input: "https://truyenvn.com/the-loai/manhwa", script: "gen.js"},
        {title: "Martial Arts", input: "https://truyenvn.com/the-loai/martial-arts", script: "gen.js"},
        {title: "Marvel Comics", input: "https://truyenvn.com/the-loai/marvel-comics", script: "gen.js"},
        {title: "Mature", input: "https://truyenvn.com/the-loai/mature", script: "gen.js"},
        {title: "Mecha", input: "https://truyenvn.com/the-loai/mecha", script: "gen.js"},
        {title: "Military", input: "https://truyenvn.com/the-loai/military", script: "gen.js"},
        {title: "Mystery", input: "https://truyenvn.com/the-loai/mystery", script: "gen.js"},
        {title: "Ngôn Tình", input: "https://truyenvn.com/the-loai/ngon-tinh", script: "gen.js"},
        {title: "One Shot", input: "https://truyenvn.com/the-loai/one-shot", script: "gen.js"},
        {title: "Psychological", input: "https://truyenvn.com/the-loai/psychological", script: "gen.js"},
        {title: "Romance", input: "https://truyenvn.com/the-loai/romance", script: "gen.js"},
        {title: "School Life", input: "https://truyenvn.com/the-loai/school-life", script: "gen.js"},
        {title: "Sci-Fi", input: "https://truyenvn.com/the-loai/sci-fi", script: "gen.js"},
        {title: "Seinen", input: "https://truyenvn.com/the-loai/seinen", script: "gen.js"},
        {title: "Shoujo", input: "https://truyenvn.com/the-loai/shoujo", script: "gen.js"},
        {title: "Shoujo Ai", input: "https://truyenvn.com/the-loai/shoujo-ai", script: "gen.js"},
        {title: "Shounen", input: "https://truyenvn.com/the-loai/shounen", script: "gen.js"},
        {title: "Shounen Ai", input: "https://truyenvn.com/the-loai/shounen-ai", script: "gen.js"},
        {title: "Slice Of Life", input: "https://truyenvn.com/the-loai/slice-of-life", script: "gen.js"},
        {title: "Smut", input: "https://truyenvn.com/the-loai/smut", script: "gen.js"},
        {title: "Soft Yaoi", input: "https://truyenvn.com/the-loai/soft-yaoi", script: "gen.js"},
        {title: "Soft Yuri", input: "https://truyenvn.com/the-loai/soft-yuri", script: "gen.js"},
        {title: "Sports", input: "https://truyenvn.com/the-loai/sports", script: "gen.js"},
        {title: "Supernatural", input: "https://truyenvn.com/the-loai/supernatural", script: "gen.js"},
        {title: "Tạp chí truyện tranh", input: "https://truyenvn.com/the-loai/tap-chi-truyen-tranh", script: "gen.js"},
        {title: "Thiếu Nhi", input: "https://truyenvn.com/the-loai/thieu-nhi", script: "gen.js"},
        {title: "Tragedy", input: "https://truyenvn.com/the-loai/tragedy", script: "gen.js"},
        {title: "Trinh Thám", input: "https://truyenvn.com/the-loai/trinh-tham", script: "gen.js"},
        {title: "Trọng Sinh", input: "https://truyenvn.com/the-loai/trong-sinh", script: "gen.js"},
        {title: "Truyện Chữ", input: "https://truyenvn.com/the-loai/truyen-chu", script: "gen.js"},
        {title: "Truyện Ma", input: "https://truyenvn.com/the-loai/truyen-ma", script: "gen.js"},
        {title: "Truyện Màu", input: "https://truyenvn.com/the-loai/truyen-mau", script: "gen.js"},
        {title: "Truyệt Tranh Việt Nam", input: "https://truyenvn.com/the-loai/truyet-tranh-viet-nam", script: "gen.js"},
        {title: "Việt Nam", input: "https://truyenvn.com/the-loai/viet-nam", script: "gen.js"},
        {title: "Webtoon", input: "https://truyenvn.com/the-loai/webtoon", script: "gen.js"},
        {title: "Xuyên Không", input: "https://truyenvn.com/the-loai/xuyen-khong", script: "gen.js"},
        {title: "Yaoi", input: "https://truyenvn.com/the-loai/yaoi", script: "gen.js"},
        {title: "Yuri", input: "https://truyenvn.com/the-loai/yuri", script: "gen.js"}
    ]);
}