load('config.js');

function execute() {
    return Response.success([
        { title: "Tiên hiệp", input: BASE_URL + "/tien-hiep/", script: "gen.js" },
        { title: "Kiếm hiệp", input: BASE_URL + "/kiem-hiep/", script: "gen.js" },
        { title: "Truyện Teen", input: BASE_URL + "/truyen-teen/", script: "gen.js" },
        { title: "Ngôn Tình", input: BASE_URL + "/ngon-tinh/", script: "gen.js" },
        { title: "Đoản Văn", input: BASE_URL + "/doan-van/", script: "gen.js" },
        { title: "Đông Phương", input: BASE_URL + "/dong-phuong/", script: "gen.js" },
        { title: "Gia Đấu", input: BASE_URL + "/gia-dau/", script: "gen.js" },
        { title: "Nữ Cường", input: BASE_URL + "/nu-cuong/", script: "gen.js" },
        { title: "Cung Đấu", input: BASE_URL + "/cung-dau/", script: "gen.js" },
        { title: "Truyện Sủng", input: BASE_URL + "/truyen-sung/", script: "gen.js" },
        { title: "Truyện Ngược", input: BASE_URL + "/truyen-nguoc/", script: "gen.js" },
        { title: "Linh Dị", input: BASE_URL + "/linh-di/", script: "gen.js" },
        { title: "Thám Hiểm", input: BASE_URL + "/tham-hiem/", script: "gen.js" },
        { title: "Bách Hợp", input: BASE_URL + "/bach-hop/", script: "gen.js" },
        { title: "Hài Hước", input: BASE_URL + "/hai-huoc/", script: "gen.js" },
        { title: "Hiện Đại", input: BASE_URL + "/hien-dai/", script: "gen.js" },
        { title: "Việt Nam", input: BASE_URL + "/viet-nam/", script: "gen.js" },
        { title: "Light Novel", input: BASE_URL + "/light-novel/", script: "gen.js" },
        { title: "Nữ Phụ", input: BASE_URL + "/nu-phu/", script: "gen.js" },
        { title: "Phương Tây", input: BASE_URL + "/phuong-tay/", script: "gen.js" },
        { title: "Mạt Thế", input: BASE_URL + "/mat-the/", script: "gen.js" },
        { title: "Cổ Đại", input: BASE_URL + "/co-dai/", script: "gen.js" },
        { title: "Điền Văn", input: BASE_URL + "/dien-van/", script: "gen.js" },
        { title: "Đồng Nhân", input: BASE_URL + "/dong-nhan/", script: "gen.js" },
        { title: "Trọng Sinh", input: BASE_URL + "/trong-sinh/", script: "gen.js" },
        { title: "Dị Năng", input: BASE_URL + "/di-nang/", script: "gen.js" },
        { title: "Huyền Huyễn", input: BASE_URL + "/huyen-huyen/", script: "gen.js" },
        { title: "Dị Giới", input: BASE_URL + "/di-gioi/", script: "gen.js" },
        { title: "Võng Du", input: BASE_URL + "/vong-du/", script: "gen.js" },
        { title: "Quân sự", input: BASE_URL + "/quan-su/", script: "gen.js" },
        { title: "Khoa học", input: BASE_URL + "/khoa-hoc/", script: "gen.js" },
        { title: "Lịch sử", input: BASE_URL + "/lich-su/", script: "gen.js" },
        { title: "Truyện Khác", input: BASE_URL + "/truyen-khac/", script: "gen.js" },
        { title: "Đô thị", input: BASE_URL + "/do-thi/", script: "gen.js" },
        { title: "Khoa Huyễn", input: BASE_URL + "/khoa-huyen/", script: "gen.js" },
        { title: "Xuyên Không", input: BASE_URL + "/xuyen-khong/", script: "gen.js" },
        { title: "Truyện ma", input: BASE_URL + "/truyen-ma/", script: "gen.js" },
        { title: "Xuyên Nhanh", input: BASE_URL + "/xuyen-nhanh/", script: "gen.js" },
        { title: "Quan Trường", input: BASE_URL + "/quan-truong/", script: "gen.js" },
        { title: "Đam Mỹ", input: BASE_URL + "/dam-my/", script: "gen.js" },
        { title: "Hệ thống", input: BASE_URL + "/he-thong/", script: "gen.js" },
        { title: "Tiểu thuyết", input: BASE_URL + "/tieu-thuyet/", script: "gen.js" },
        { title: "Truyện Cười", input: BASE_URL + "/truyen-cuoi/", script: "gen.js" },
        { title: "Truyện Ngắn", input: BASE_URL + "/truyen-ngan/", script: "gen.js" },
        { title: "Truyện trinh thám", input: BASE_URL + "/truyen-trinh-tham/", script: "gen.js" },
        { title: "Truyện Sắc", input: BASE_URL + "/truyen-sac/", script: "gen.js" }
    ]);
}