function execute() {
    return Response.success([
        { title: "Tiên hiệp", input: "https://dtruyen.com/tien-hiep/", script: "gen.js" },
        { title: "Kiếm hiệp", input: "https://dtruyen.com/kiem-hiep/", script: "gen.js" },
        { title: "Truyện Teen", input: "https://dtruyen.com/truyen-teen/", script: "gen.js" },
        { title: "Ngôn Tình", input: "https://dtruyen.com/ngon-tinh/", script: "gen.js" },
        { title: "Đoản Văn", input: "https://dtruyen.com/doan-van/", script: "gen.js" },
        { title: "Đông Phương", input: "https://dtruyen.com/dong-phuong/", script: "gen.js" },
        { title: "Gia Đấu", input: "https://dtruyen.com/gia-dau/", script: "gen.js" },
        { title: "Nữ Cường", input: "https://dtruyen.com/nu-cuong/", script: "gen.js" },
        { title: "Cung Đấu", input: "https://dtruyen.com/cung-dau/", script: "gen.js" },
        { title: "Truyện Sủng", input: "https://dtruyen.com/truyen-sung/", script: "gen.js" },
        { title: "Truyện Ngược", input: "https://dtruyen.com/truyen-nguoc/", script: "gen.js" },
        { title: "Linh Dị", input: "https://dtruyen.com/linh-di/", script: "gen.js" },
        { title: "Thám Hiểm", input: "https://dtruyen.com/tham-hiem/", script: "gen.js" },
        { title: "Bách Hợp", input: "https://dtruyen.com/bach-hop/", script: "gen.js" },
        { title: "Hài Hước", input: "https://dtruyen.com/hai-huoc/", script: "gen.js" },
        { title: "Hiện Đại", input: "https://dtruyen.com/hien-dai/", script: "gen.js" },
        { title: "Việt Nam", input: "https://dtruyen.com/viet-nam/", script: "gen.js" },
        { title: "Light Novel", input: "https://dtruyen.com/light-novel/", script: "gen.js" },
        { title: "Nữ Phụ", input: "https://dtruyen.com/nu-phu/", script: "gen.js" },
        { title: "Phương Tây", input: "https://dtruyen.com/phuong-tay/", script: "gen.js" },
        { title: "Mạt Thế", input: "https://dtruyen.com/mat-the/", script: "gen.js" },
        { title: "Cổ Đại", input: "https://dtruyen.com/co-dai/", script: "gen.js" },
        { title: "Điền Văn", input: "https://dtruyen.com/dien-van/", script: "gen.js" },
        { title: "Đồng Nhân", input: "https://dtruyen.com/dong-nhan/", script: "gen.js" },
        { title: "Trọng Sinh", input: "https://dtruyen.com/trong-sinh/", script: "gen.js" },
        { title: "Dị Năng", input: "https://dtruyen.com/di-nang/", script: "gen.js" },
        { title: "Huyền Huyễn", input: "https://dtruyen.com/huyen-huyen/", script: "gen.js" },
        { title: "Dị Giới", input: "https://dtruyen.com/di-gioi/", script: "gen.js" },
        { title: "Võng Du", input: "https://dtruyen.com/vong-du/", script: "gen.js" },
        { title: "Quân sự", input: "https://dtruyen.com/quan-su/", script: "gen.js" },
        { title: "Khoa học", input: "https://dtruyen.com/khoa-hoc/", script: "gen.js" },
        { title: "Lịch sử", input: "https://dtruyen.com/lich-su/", script: "gen.js" },
        { title: "Truyện Khác", input: "https://dtruyen.com/truyen-khac/", script: "gen.js" },
        { title: "Đô thị", input: "https://dtruyen.com/do-thi/", script: "gen.js" },
        { title: "Khoa Huyễn", input: "https://dtruyen.com/khoa-huyen/", script: "gen.js" },
        { title: "Xuyên Không", input: "https://dtruyen.com/xuyen-khong/", script: "gen.js" },
        { title: "Truyện ma", input: "https://dtruyen.com/truyen-ma/", script: "gen.js" },
        { title: "Xuyên Nhanh", input: "https://dtruyen.com/xuyen-nhanh/", script: "gen.js" },
        { title: "Quan Trường", input: "https://dtruyen.com/quan-truong/", script: "gen.js" },
        { title: "Đam Mỹ", input: "https://dtruyen.com/dam-my/", script: "gen.js" },
        { title: "Hệ thống", input: "https://dtruyen.com/he-thong/", script: "gen.js" },
        { title: "Tiểu thuyết", input: "https://dtruyen.com/tieu-thuyet/", script: "gen.js" },
        { title: "Truyện Cười", input: "https://dtruyen.com/truyen-cuoi/", script: "gen.js" },
        { title: "Truyện Ngắn", input: "https://dtruyen.com/truyen-ngan/", script: "gen.js" },
        { title: "Truyện trinh thám", input: "https://dtruyen.com/truyen-trinh-tham/", script: "gen.js" },
        { title: "Truyện Sắc", input: "https://dtruyen.com/truyen-sac/", script: "gen.js" }
    ]);
}