function execute() {
    return Response.success([
        {title: "Bách Hợp", input: "https://s2.truyenhd.com/keyword/bach-hop", script: "gen.js"},
        {title: "Cổ Đại", input: "https://s2.truyenhd.com/keyword/co-dai", script: "gen.js"},
        {title: "Dị Giới", input: "https://s2.truyenhd.com/keyword/di-gioi", script: "gen.js"},
        {title: "Dị Năng", input: "https://s2.truyenhd.com/keyword/di-nang", script: "gen.js"},
        {title: "Huyền Huyễn", input: "https://s2.truyenhd.com/keyword/huyen-huyen", script: "gen.js"},
        {title: "Hài Hước", input: "https://s2.truyenhd.com/keyword/hai-huoc", script: "gen.js"},
        {title: "Hắc Bang", input: "https://s2.truyenhd.com/keyword/hac-bang", script: "gen.js"},
        {title: "Hệ Thống", input: "https://s2.truyenhd.com/keyword/he-thong", script: "gen.js"},
        {title: "Khoa Huyễn", input: "https://s2.truyenhd.com/keyword/khoa-huyen", script: "gen.js"},
        {title: "Kiếm Hiệp", input: "https://s2.truyenhd.com/keyword/kiem-hiep", script: "gen.js"},
        {title: "Kỳ Huyễn", input: "https://s2.truyenhd.com/keyword/ky-huyen", script: "gen.js"},
        {title: "Linh Dị", input: "https://s2.truyenhd.com/keyword/linh-di", script: "gen.js"},
        {title: "Mạt Thế", input: "https://s2.truyenhd.com/keyword/mat-the", script: "gen.js"},
        {title: "Ngôn Tình", input: "https://s2.truyenhd.com/keyword/ngon-tinh", script: "gen.js"},
        {title: "Ngược", input: "https://s2.truyenhd.com/keyword/nguoc", script: "gen.js"},
        {title: "Phương Tây", input: "https://s2.truyenhd.com/keyword/phuong-tay", script: "gen.js"},
        {title: "Quan Trường", input: "https://s2.truyenhd.com/keyword/quan-truong", script: "gen.js"},
        {title: "Quân Nhân", input: "https://s2.truyenhd.com/keyword/quan-nhan", script: "gen.js"},
        {title: "Showbiz", input: "https://s2.truyenhd.com/keyword/showbiz", script: "gen.js"},
        {title: "Sắc", input: "https://s2.truyenhd.com/keyword/sac", script: "gen.js"},
        {title: "Sủng", input: "https://s2.truyenhd.com/keyword/sung", script: "gen.js"},
        {title: "Tiên Hiệp", input: "https://s2.truyenhd.com/keyword/tien-hiep", script: "gen.js"},
        {title: "Trinh Thám", input: "https://s2.truyenhd.com/keyword/trinh-tham", script: "gen.js"},
        {title: "Truyện 18+", input: "https://s2.truyenhd.com/keyword/truyen-sex", script: "gen.js"},
        {title: "Truyện Gay", input: "https://s2.truyenhd.com/keyword/gay", script: "gen.js"},
        {title: "Truyện Les", input: "https://s2.truyenhd.com/keyword/les", script: "gen.js"},
        {title: "Truyện Teen", input: "https://s2.truyenhd.com/keyword/teen", script: "gen.js"},
        {title: "Truyện Tranh", input: "https://s2.truyenhd.com/keyword/truyen-tranh", script: "gen.js"},
        {title: "Truyện Voz", input: "https://s2.truyenhd.com/keyword/voz", script: "gen.js"},
        {title: "Trọng Sinh", input: "https://s2.truyenhd.com/keyword/trong-sinh", script: "gen.js"},
        {title: "Võng Du", input: "https://s2.truyenhd.com/keyword/vong-du", script: "gen.js"},
        {title: "Xuyên Không", input: "https://s2.truyenhd.com/keyword/xuyen-khong", script: "gen.js"},
        {title: "Xuyên Nhanh", input: "https://s2.truyenhd.com/keyword/xuyen-nhanh", script: "gen.js"},
        {title: "Zombie", input: "https://s2.truyenhd.com/keyword/zombie", script: "gen.js"},
        {title: "Đam Mỹ", input: "https://s2.truyenhd.com/keyword/dam-my", script: "gen.js"},
        {title: "Đô Thị", input: "https://s2.truyenhd.com/keyword/do-thi", script: "gen.js"},
        {title: "Đồng Nhân", input: "https://s2.truyenhd.com/keyword/dong-nhan", script: "gen.js"}
    ]);
}