function execute() {
    return Response.success([
            {title: "Sắc", input: "sac", script: "gen.js"},
            {title: "Ngôn Tình", input: "ngon-tinh", script: "gen.js"},
            {title: "Đam Mỹ", input: "dam-my", script: "gen.js"},
            {title: "Đô Thị", input: "do-thi", script: "gen.js"},
            {title: "Cung Đấu", input: "cung-dau", script: "gen.js"},
            {title: "Dị Giới", input: "di-gioi", script: "gen.js"},
            {title: "Điền Văn", input: "dien-van", script: "gen.js"},
            {title: "Gia Đấu", input: "gia-dau", script: "gen.js"},
            {title: "Hài Hước", input: "hai-hoc", script: "gen.js"},
            {title: "Hay Hot", input: "hay-hot", script: "gen.js"},
            {title: "Hiện Đại", input: "hien-dai", script: "gen.js"},
            {title: "Hoàn Thành", input: "hoan-thanh", script: "gen.js"},
            {title: "Học Đường", input: "hoc-duong", script: "gen.js"},
            {title: "Huyền Huyễn", input: "huyen-huyen", script: "gen.js"},
            {title: "Kiếm Hiệp", input: "kiem-hiep", script: "gen.js"},
            {title: "Lịch sử", input: "lich-su", script: "gen.js"},
            {title: "Mạt Thế", input: "mat-the", script: "gen.js"},
            {title: "Cổ Đại", input: "co-dai", script: "gen.js"},
            {title: "Ngọt", input: "ngot", script: "gen.js"},
            {title: "Ngược", input: "nguoc", script: "gen.js"},
            {title: "Nữ Cường", input: "nu-cuong", script: "gen.js"},
            {title: "Nữ Phụ", input: "nu-phu", script: "gen.js"},
            {title: "Quân Nhân", input: "quan-nhan", script: "gen.js"},
            {title: "Đông Phương", input: "dong-phuong", script: "gen.js"},
            {title: "Quân Sự", input: "quan-su", script: "gen.js"},
            {title: "Quan Trường", input: "quan-truong", script: "gen.js"},
            {title: "Sủng", input: "sung", script: "gen.js"},
            {title: "Bách Hợp", input: "bach-hop", script: "gen.js"},
            {title: "Tiểu Thuyết", input: "tien-hiep", script: "gen.js"},
            {title: "Tình Yêu", input: "tieu-thuyet", script: "gen.js"},
            {title: "Tình Yêu", input: "tinh-yeu", script: "gen.js"},
            {title: "Trọng Sinh", input: "trong-sinh", script: "gen.js"},
            {title: "Truyện Ngắn", input: "truyen-ma-kinh-di", script: "gen.js"},
            {title: "Truyện Teen", input: "truyen-ngan", script: "gen.js"},
            {title: "Võng Du", input: "truyen-teen", script: "gen.js"},
            {title: "Xuyên Không", input: "xuyen-khong", script: "gen.js"},
    ]);
}