function execute() {
    return Response.success([
        {title: "Action", input: "https://readmanga.org/genre/action", script: "gen.js"},
        {title: "Adventure", input: "https://readmanga.org/genre/adventure", script: "gen.js"},
        {title: "All Categories", input: "https://readmanga.org/genre/index", script: "gen.js"},
        {title: "Comedy", input: "https://readmanga.org/genre/comedy", script: "gen.js"},
        {title: "Cooking", input: "https://readmanga.org/genre/cooking", script: "gen.js"},
        {title: "Doujinshi", input: "https://readmanga.org/genre/doujinshi", script: "gen.js"},
        {title: "Drama", input: "https://readmanga.org/genre/drama", script: "gen.js"},
        {title: "Ecchi", input: "https://readmanga.org/genre/ecchi", script: "gen.js"},
        {title: "Fantasy", input: "https://readmanga.org/genre/fantasy", script: "gen.js"},
        {title: "Gender Bender", input: "https://readmanga.org/genre/gender-bender", script: "gen.js"},
        {title: "Harem", input: "https://readmanga.org/genre/harem", script: "gen.js"},
        {title: "Historical", input: "https://readmanga.org/genre/historical", script: "gen.js"},
        {title: "Horror", input: "https://readmanga.org/genre/horror", script: "gen.js"},
        {title: "Isekai", input: "https://readmanga.org/genre/isekai", script: "gen.js"},
        {title: "Josei", input: "https://readmanga.org/genre/josei", script: "gen.js"},
        {title: "Lolicon", input: "https://readmanga.org/genre/lolicon", script: "gen.js"},
        {title: "Magic", input: "https://readmanga.org/genre/magic", script: "gen.js"},
        {title: "Manga", input: "https://readmanga.org/genre/manga", script: "gen.js"},
        {title: "Manhua", input: "https://readmanga.org/genre/manhua", script: "gen.js"},
        {title: "Manhwa", input: "https://readmanga.org/genre/manhwa", script: "gen.js"},
        {title: "Martial Arts", input: "https://readmanga.org/genre/martial-arts", script: "gen.js"},
        {title: "Mature", input: "https://readmanga.org/genre/mature", script: "gen.js"},
        {title: "Mecha", input: "https://readmanga.org/genre/mecha", script: "gen.js"},
        {title: "Mind Game", input: "https://readmanga.org/genre/mind-game", script: "gen.js"},
        {title: "Mystery", input: "https://readmanga.org/genre/mystery", script: "gen.js"},
        {title: "None", input: "https://readmanga.org/genre/none", script: "gen.js"},
        {title: "One shot", input: "https://readmanga.org/genre/one-shot", script: "gen.js"},
        {title: "Psychological", input: "https://readmanga.org/genre/psychological", script: "gen.js"},
        {title: "Recarnation", input: "https://readmanga.org/genre/recarnation", script: "gen.js"},
        {title: "Romance", input: "https://readmanga.org/genre/romance", script: "gen.js"},
        {title: "School Life", input: "https://readmanga.org/genre/school-life", script: "gen.js"},
        {title: "Sci fi", input: "https://readmanga.org/genre/sci-fi", script: "gen.js"},
        {title: "Seinen", input: "https://readmanga.org/genre/seinen", script: "gen.js"},
        {title: "Shotacon", input: "https://readmanga.org/genre/shotacon", script: "gen.js"},
        {title: "Shoujo", input: "https://readmanga.org/genre/shoujo", script: "gen.js"},
        {title: "Shoujo Ai", input: "https://readmanga.org/genre/shoujo-ai", script: "gen.js"},
        {title: "Shounen", input: "https://readmanga.org/genre/shounen", script: "gen.js"},
        {title: "Shounen Ai", input: "https://readmanga.org/genre/shounen-ai", script: "gen.js"},
        {title: "Slice of Life", input: "https://readmanga.org/genre/slice-of-life", script: "gen.js"},
        {title: "Sports", input: "https://readmanga.org/genre/sports", script: "gen.js"},
        {title: "Supernatural", input: "https://readmanga.org/genre/supernatural", script: "gen.js"},
        {title: "Time Travel", input: "https://readmanga.org/genre/time-travel", script: "gen.js"},
        {title: "Tragedy", input: "https://readmanga.org/genre/tragedy", script: "gen.js"},
        {title: "Uncategorized", input: "https://readmanga.org/genre/uncategorized", script: "gen.js"},
        {title: "Yaoi", input: "https://readmanga.org/genre/yaoi", script: "gen.js"},
        {title: "Yuri", input: "https://readmanga.org/genre/yuri", script: "gen.js"}
    ]);
}