load('config.js');
function execute() {
    return Response.success([
        {title: "Bách Hợp", input: BASE_URL + "/keyword/bach-hop", script: "gen.js"},
        {title: "Cổ Đại", input: BASE_URL + "/keyword/co-dai", script: "gen.js"},
        {title: "Dị Giới", input: BASE_URL + "/keyword/di-gioi", script: "gen.js"},
        {title: "Dị Năng", input: BASE_URL + "/keyword/di-nang", script: "gen.js"},
        {title: "Huyền Huyễn", input: BASE_URL + "/keyword/huyen-huyen", script: "gen.js"},
        {title: "Hài Hước", input: BASE_URL + "/keyword/hai-huoc", script: "gen.js"},
        {title: "Hắc Bang", input: BASE_URL + "/keyword/hac-bang", script: "gen.js"},
        {title: "Hệ Thống", input: BASE_URL + "/keyword/he-thong", script: "gen.js"},
        {title: "Khoa Huyễn", input: BASE_URL + "/keyword/khoa-huyen", script: "gen.js"},
        {title: "Kiếm Hiệp", input: BASE_URL + "/keyword/kiem-hiep", script: "gen.js"},
        {title: "Kỳ Huyễn", input: BASE_URL + "/keyword/ky-huyen", script: "gen.js"},
        {title: "Linh Dị", input: BASE_URL + "/keyword/linh-di", script: "gen.js"},
        {title: "Mạt Thế", input: BASE_URL + "/keyword/mat-the", script: "gen.js"},
        {title: "Ngôn Tình", input: BASE_URL + "/keyword/ngon-tinh", script: "gen.js"},
        {title: "Ngược", input: BASE_URL + "/keyword/nguoc", script: "gen.js"},
        {title: "Phương Tây", input: BASE_URL + "/keyword/phuong-tay", script: "gen.js"},
        {title: "Quan Trường", input: BASE_URL + "/keyword/quan-truong", script: "gen.js"},
        {title: "Quân Nhân", input: BASE_URL + "/keyword/quan-nhan", script: "gen.js"},
        {title: "Showbiz", input: BASE_URL + "/keyword/showbiz", script: "gen.js"},
        {title: "Sắc", input: BASE_URL + "/keyword/sac", script: "gen.js"},
        {title: "Sủng", input: BASE_URL + "/keyword/sung", script: "gen.js"},
        {title: "Tiên Hiệp", input: BASE_URL + "/keyword/tien-hiep", script: "gen.js"},
        {title: "Trinh Thám", input: BASE_URL + "/keyword/trinh-tham", script: "gen.js"},
        {title: "Truyện 18+", input: BASE_URL + "/keyword/truyen-sex", script: "gen.js"},
        {title: "Truyện Gay", input: BASE_URL + "/keyword/gay", script: "gen.js"},
        {title: "Truyện Les", input: BASE_URL + "/keyword/les", script: "gen.js"},
        {title: "Truyện Teen", input: BASE_URL + "/keyword/teen", script: "gen.js"},
        {title: "Truyện Tranh", input: BASE_URL + "/keyword/truyen-tranh", script: "gen.js"},
        {title: "Truyện Voz", input: BASE_URL + "/keyword/voz", script: "gen.js"},
        {title: "Trọng Sinh", input: BASE_URL + "/keyword/trong-sinh", script: "gen.js"},
        {title: "Võng Du", input: BASE_URL + "/keyword/vong-du", script: "gen.js"},
        {title: "Xuyên Không", input: BASE_URL + "/keyword/xuyen-khong", script: "gen.js"},
        {title: "Xuyên Nhanh", input: BASE_URL + "/keyword/xuyen-nhanh", script: "gen.js"},
        {title: "Zombie", input: BASE_URL + "/keyword/zombie", script: "gen.js"},
        {title: "Đam Mỹ", input: BASE_URL + "/keyword/dam-my", script: "gen.js"},
        {title: "Đô Thị", input: BASE_URL + "/keyword/do-thi", script: "gen.js"},
        {title: "Đồng Nhân", input: BASE_URL + "/keyword/dong-nhan", script: "gen.js"}
    ]);
}