local genre = {}
table.insert(genre, { ["title"] = "Action", ["input"] = "https://ln.hako.re/the-loai/action", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Adapted to Anime", ["input"] = "https://ln.hako.re/the-loai/adapted-to-anime", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Adapted to Drama CD", ["input"] = "https://ln.hako.re/the-loai/adapted-to-drama-cd", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Adapted to Manga", ["input"] = "https://ln.hako.re/the-loai/adapted-to-manga", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Adult", ["input"] = "https://ln.hako.re/the-loai/adult", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Adventure", ["input"] = "https://ln.hako.re/the-loai/adventure", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Chinese Novel", ["input"] = "https://ln.hako.re/the-loai/chinese-novel", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Comedy", ["input"] = "https://ln.hako.re/the-loai/comedy", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Cooking", ["input"] = "https://ln.hako.re/the-loai/cooking", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Drama", ["input"] = "https://ln.hako.re/the-loai/drama", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Ecchi", ["input"] = "https://ln.hako.re/the-loai/ecchi", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "English Novel", ["input"] = "https://ln.hako.re/the-loai/english-novel", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Fantasy", ["input"] = "https://ln.hako.re/the-loai/fantasy", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Game", ["input"] = "https://ln.hako.re/the-loai/game", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Gender Bender", ["input"] = "https://ln.hako.re/the-loai/gender-bender", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Harem", ["input"] = "https://ln.hako.re/the-loai/harem", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Historical", ["input"] = "https://ln.hako.re/the-loai/historical", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Horror", ["input"] = "https://ln.hako.re/the-loai/horror", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Incest", ["input"] = "https://ln.hako.re/the-loai/incest", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Isekai", ["input"] = "https://ln.hako.re/the-loai/isekai", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Josei", ["input"] = "https://ln.hako.re/the-loai/josei", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Korean Novel", ["input"] = "https://ln.hako.re/the-loai/korean-novel", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Magic", ["input"] = "https://ln.hako.re/the-loai/magic", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Martial Arts", ["input"] = "https://ln.hako.re/the-loai/martial-arts", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Mature", ["input"] = "https://ln.hako.re/the-loai/mature", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Mecha", ["input"] = "https://ln.hako.re/the-loai/mecha", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Military", ["input"] = "https://ln.hako.re/the-loai/military", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Mystery", ["input"] = "https://ln.hako.re/the-loai/mystery", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Netorare", ["input"] = "https://ln.hako.re/the-loai/netorare", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "One shot", ["input"] = "https://ln.hako.re/the-loai/one-shot", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Otome Game", ["input"] = "https://ln.hako.re/the-loai/otome-game", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Psychological", ["input"] = "https://ln.hako.re/the-loai/psychological", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Reverse Harem", ["input"] = "https://ln.hako.re/the-loai/reverse-harem", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Romance", ["input"] = "https://ln.hako.re/the-loai/romance", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "School Life", ["input"] = "https://ln.hako.re/the-loai/school-life", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Science Fiction", ["input"] = "https://ln.hako.re/the-loai/science-fiction", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Seinen", ["input"] = "https://ln.hako.re/the-loai/seinen", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Shoujo", ["input"] = "https://ln.hako.re/the-loai/shoujo", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Shoujo ai", ["input"] = "https://ln.hako.re/the-loai/shoujo-ai", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Shounen", ["input"] = "https://ln.hako.re/the-loai/shounen", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Shounen ai", ["input"] = "https://ln.hako.re/the-loai/shounen-ai", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Slice of Life", ["input"] = "https://ln.hako.re/the-loai/slice-of-life", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Sports", ["input"] = "https://ln.hako.re/the-loai/sports", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Super Power", ["input"] = "https://ln.hako.re/the-loai/super-power", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Supernatural", ["input"] = "https://ln.hako.re/the-loai/supernatural", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Suspense", ["input"] = "https://ln.hako.re/the-loai/suspense", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Tragedy", ["input"] = "https://ln.hako.re/the-loai/tragedy", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Web Novel", ["input"] = "https://ln.hako.re/the-loai/web-novel", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Yuri", ["input"] = "https://ln.hako.re/the-loai/yuri", ["script"] = "gen.lua" })
return response:success(genre)