function execute() {
    return Response.success([
        {title: "Toàn bộ", input: "https://www.medoctruyentranh.net/tim-truyen/toan-bo", script: "gen.js"},
        {title: "Xuyên không", input: "https://www.medoctruyentranh.net/tim-truyen/xuyen-khong", script: "gen.js"},
        {title: "Manhua", input: "https://www.medoctruyentranh.net/tim-truyen/manhua", script: "gen.js"},
        {title: "Cổ Đại", input: "https://www.medoctruyentranh.net/tim-truyen/co-dai", script: "gen.js"},
        {title: "Action", input: "https://www.medoctruyentranh.net/tim-truyen/action", script: "gen.js"},
        {title: "Đam Mỹ", input: "https://www.medoctruyentranh.net/tim-truyen/dam-my", script: "gen.js"},
        {title: "Manga", input: "https://www.medoctruyentranh.net/tim-truyen/manga", script: "gen.js"},
        {title: "Adventure", input: "https://www.medoctruyentranh.net/tim-truyen/adventure", script: "gen.js"},
        {title: "Comedy", input: "https://www.medoctruyentranh.net/tim-truyen/comedy", script: "gen.js"},
        {title: "Cooking", input: "https://www.medoctruyentranh.net/tim-truyen/cooking", script: "gen.js"},
        {title: "Comic", input: "https://www.medoctruyentranh.net/tim-truyen/comic", script: "gen.js"},
        {title: "Drama", input: "https://www.medoctruyentranh.net/tim-truyen/drama", script: "gen.js"},
        {title: "Fantasy", input: "https://www.medoctruyentranh.net/tim-truyen/fantasy", script: "gen.js"},
        {title: "Gender Bender", input: "https://www.medoctruyentranh.net/tim-truyen/gender-bender", script: "gen.js"},
        {title: "Harem", input: "https://www.medoctruyentranh.net/tim-truyen/harem", script: "gen.js"},
        {title: "Historical", input: "https://www.medoctruyentranh.net/tim-truyen/historical", script: "gen.js"},
        {title: "Horror", input: "https://www.medoctruyentranh.net/tim-truyen/horror", script: "gen.js"},
        {title: "Josei", input: "https://www.medoctruyentranh.net/tim-truyen/josei", script: "gen.js"},
        {title: "Art Book", input: "https://www.medoctruyentranh.net/tim-truyen/art-book", script: "gen.js"},
        {title: "Manhwa", input: "https://www.medoctruyentranh.net/tim-truyen/manhwa", script: "gen.js"},
        {title: "Martial Arts", input: "https://www.medoctruyentranh.net/tim-truyen/martial-arts", script: "gen.js"},
        {title: "Mecha", input: "https://www.medoctruyentranh.net/tim-truyen/mecha", script: "gen.js"},
        {title: "Mystery", input: "https://www.medoctruyentranh.net/tim-truyen/mystery", script: "gen.js"},
        {title: "One Shot", input: "https://www.medoctruyentranh.net/tim-truyen/one-shot", script: "gen.js"},
        {title: "Psychological", input: "https://www.medoctruyentranh.net/tim-truyen/psychological", script: "gen.js"},
        {title: "Romance", input: "https://www.medoctruyentranh.net/tim-truyen/romance", script: "gen.js"},
        {title: "School Life", input: "https://www.medoctruyentranh.net/tim-truyen/school-life", script: "gen.js"},
        {title: "Sci-fi", input: "https://www.medoctruyentranh.net/tim-truyen/sci-fi", script: "gen.js"},
        {title: "Seinen", input: "https://www.medoctruyentranh.net/tim-truyen/seinen", script: "gen.js"},
        {title: "Shoujo", input: "https://www.medoctruyentranh.net/tim-truyen/shoujo", script: "gen.js"},
        {title: "Shoujo-ai", input: "https://www.medoctruyentranh.net/tim-truyen/shoujo-ai", script: "gen.js"},
        {title: "Shounen", input: "https://www.medoctruyentranh.net/tim-truyen/shounen", script: "gen.js"},
        {title: "Shounen-ai", input: "https://www.medoctruyentranh.net/tim-truyen/shounen-ai", script: "gen.js"},
        {title: "Slice of Life", input: "https://www.medoctruyentranh.net/tim-truyen/slice-of-life", script: "gen.js"},
        {title: "Sports", input: "https://www.medoctruyentranh.net/tim-truyen/sports", script: "gen.js"},
        {title: "Supernatural", input: "https://www.medoctruyentranh.net/tim-truyen/supernatural", script: "gen.js"},
        {title: "Tragedy", input: "https://www.medoctruyentranh.net/tim-truyen/tragedy", script: "gen.js"},
        {title: "Anime", input: "https://www.medoctruyentranh.net/tim-truyen/anime", script: "gen.js"},
        {title: "Doujinshi", input: "https://www.medoctruyentranh.net/tim-truyen/doujinshi", script: "gen.js"},
        {title: "Live action", input: "https://www.medoctruyentranh.net/tim-truyen/live-action", script: "gen.js"},
        {title: "Magic", input: "https://www.medoctruyentranh.net/tim-truyen/magic", script: "gen.js"},
        {title: "Tạp chí truyện tranh", input: "https://www.medoctruyentranh.net/tim-truyen/tap-chi-truyen-tranh", script: "gen.js"},
        {title: "Trinh Thám", input: "https://www.medoctruyentranh.net/tim-truyen/trinh-tham", script: "gen.js"},
        {title: "Truyện scan", input: "https://www.medoctruyentranh.net/tim-truyen/truyen-scan", script: "gen.js"},
        {title: "VnComic", input: "https://www.medoctruyentranh.net/tim-truyen/vncomic", script: "gen.js"},
        {title: "Webtoon", input: "https://www.medoctruyentranh.net/tim-truyen/webtoon", script: "gen.js"},
        {title: "Toàn bộ", input: "https://www.medoctruyentranh.net/tim-truyen/dam-my", script: "gen.js"}
    ]);
}