load('config.js');
function execute() {
    return Response.success([
        {title: "Huyền Huyễn", input: BASE_URL + "/truyen-huyen-huyen/danh-sach/", script: "gen.js"},
        {title: "Kiếm Hiệp", input: BASE_URL + "/truyen-kiem-hiep/danh-sach/", script: "gen.js"},
        {title: "Lịch Sử", input: BASE_URL + "/truyen-lich-su/danh-sach/", script: "gen.js"},
        {title: "Ngôn Tình", input: BASE_URL + "/truyen-ngon-tinh/danh-sach/", script: "gen.js"},
        {title: "Sắc Hiệp", input: BASE_URL + "/truyen-sac-hiep/danh-sach/", script: "gen.js"},
        {title: "Tiên Hiệp", input: BASE_URL + "/truyen-tien-hiep/danh-sach/", script: "gen.js"},
        {title: "Dị Giới", input: BASE_URL + "/truyen-di-gioi/danh-sach/", script: "gen.js"},
        {title: "Đô Thị", input: BASE_URL + "/truyen-do-thi/danh-sach/", script: "gen.js"},
        {title: "Huyền Ảo", input: BASE_URL + "/truyen-huyen-ao/danh-sach/", script: "gen.js"},
        {title: "Trinh Thám", input: BASE_URL + "/truyen-trinh-tham/danh-sach/", script: "gen.js"},
        {title: "Cổ Đại", input: BASE_URL + "/truyen-co-dai/danh-sach/", script: "gen.js"},
        {title: "Hệ Thống", input: BASE_URL + "/truyen-he-thong/danh-sach/", script: "gen.js"},
        {title: "Khoa Huyễn", input: BASE_URL + "/truyen-khoa-huyen/danh-sach/", script: "gen.js"},
        {title: "Quân Sự", input: BASE_URL + "/truyen-quan-su/danh-sach/", script: "gen.js"},
        {title: "Võng Du", input: BASE_URL + "/truyen-vong-du/danh-sach/", script: "gen.js"},
        {title: "Xuyên Không", input: BASE_URL + "/truyen-xuyen-khong/danh-sach/", script: "gen.js"},
        {title: "Cổ Tiên Hiệp", input: BASE_URL + "/truyen-co-tien-hiep/danh-sach/", script: "gen.js"},
        {title: "Đam Mỹ", input: BASE_URL + "/truyen-dam-my/danh-sach/", script: "gen.js"},
        {title: "Huyền Bí", input: BASE_URL + "/truyen-huyen-bi/danh-sach/", script: "gen.js"},
        {title: "Kỳ Huyễn", input: BASE_URL + "/truyen-ky-huyen/danh-sach/", script: "gen.js"},
        {title: "Linh Dị", input: BASE_URL + "/truyen-linh-di/danh-sach/", script: "gen.js"},
        {title: "Ma Pháp", input: BASE_URL + "/truyen-huyen-huyen-ma-phap/danh-sach/", script: "gen.js"},
        {title: "Mạt Thế", input: BASE_URL + "/truyen-mat-the/danh-sach/", script: "gen.js"},
        {title: "Quan Trường", input: BASE_URL + "/truyen-quan-truong/danh-sach/", script: "gen.js"},
        {title: "Thể Thao", input: BASE_URL + "/truyen-the-thao/danh-sach/", script: "gen.js"},
        {title: "Tu Chân", input: BASE_URL + "/truyen-tu-chan-tieu-thuyet/danh-sach/", script: "gen.js"},
        {title: "Hiện Đại", input: BASE_URL + "/truyen-hien-dai/danh-sach/", script: "gen.js"},
        {title: "Bách Hợp", input: BASE_URL + "/truyen-bach-hop/danh-sach/", script: "gen.js"},
        {title: "Bình Đạm", input: BASE_URL + "/truyen-binh-dam/danh-sach/", script: "gen.js"},
        {title: "Cạnh Kỹ", input: BASE_URL + "/truyen-canh-ky/danh-sach/", script: "gen.js"},
        {title: "Cổ Đại Ngôn Tình", input: BASE_URL + "/truyen-co-dai-ngon-tinh/danh-sach/", script: "gen.js"},
        {title: "Cung Đấu", input: BASE_URL + "/truyen-cung-dau/danh-sach/", script: "gen.js"},
        {title: "Đặc Sắc", input: BASE_URL + "/truyen-sac/danh-sach/", script: "gen.js"},
        {title: "Điền Văn", input: BASE_URL + "/truyen-dien-van/danh-sach/", script: "gen.js"},
        {title: "Dị Năng", input: BASE_URL + "/truyen-di-nang/danh-sach/", script: "gen.js"},
        {title: "Đoản Văn", input: BASE_URL + "/truyen-doan-van/danh-sach/", script: "gen.js"},
        {title: "Đồng Nhân", input: BASE_URL + "/truyen-dong-nhan/danh-sach/", script: "gen.js"},
        {title: "Đông Phương", input: BASE_URL + "/truyen-dong-phuong/danh-sach/", script: "gen.js"},
        {title: "Gia Đấu", input: BASE_URL + "/truyen-gia-dau/danh-sach/", script: "gen.js"},
        {title: "Hài Hước", input: BASE_URL + "/truyen-hai-huoc/danh-sach/", script: "gen.js"},
        {title: "Hiện Đại Ngôn Tình", input: BASE_URL + "/truyen-hien-dai-ngon-tinh/danh-sach/", script: "gen.js"},
        {title: "Hồng Hoang", input: BASE_URL + "/truyen-hong-hoang/danh-sach/", script: "gen.js"},
        {title: "Huyền Huyễn Ngôn Tình", input: BASE_URL + "/truyen-huyen-huyen-ngon-tinh/danh-sach/", script: "gen.js"},
        {title: "Huyền Nghi", input: BASE_URL + "/truyen-huyen-nghi/danh-sach/", script: "gen.js"},
        {title: "Huyền Nghi Thần Quái", input: BASE_URL + "/truyen-huyen-nghi-than-quai/danh-sach/", script: "gen.js"},
        {title: "Khác", input: BASE_URL + "/truyen-khac/danh-sach/", script: "gen.js"},
        {title: "Khoa Huyễn Không Gian", input: BASE_URL + "/truyen-khoa-huyen-khong-gian/danh-sach/", script: "gen.js"},
        {title: "Kỳ Ảo", input: BASE_URL + "/truyen-ky-ao/danh-sach/", script: "gen.js"},
        {title: "Lãng Mạn Thanh Xuân", input: BASE_URL + "/truyen-lang-man-thanh-xuan/danh-sach/", script: "gen.js"},
        {title: "Light Novel", input: BASE_URL + "/truyen-light-novel/danh-sach/", script: "gen.js"},
        {title: "Ngược", input: BASE_URL + "/truyen-nguoc/danh-sach/", script: "gen.js"},
        {title: "Nhàn Hưu", input: BASE_URL + "/truyen-nhan-huu/danh-sach/", script: "gen.js"},
        {title: "Nhiều Converter", input: BASE_URL + "/truyen-nhieu-converter/danh-sach/", script: "gen.js"},
        {title: "Nữ Cường", input: BASE_URL + "/truyen-nu-cuong/danh-sach/", script: "gen.js"},
        {title: "Nữ Hiệp", input: BASE_URL + "/truyen-nu-hiep/danh-sach/", script: "gen.js"},
        {title: "Nữ Phụ", input: BASE_URL + "/truyen-nu-phu/danh-sach/", script: "gen.js"},
        {title: "Phiêu Lưu", input: BASE_URL + "/truyen-phieu-luu/danh-sach/", script: "gen.js"},
        {title: "Phương Tây", input: BASE_URL + "/truyen-phuong-tay/danh-sach/", script: "gen.js"},
        {title: "Sắc", input: BASE_URL + "/truyen-sac-2/danh-sach/", script: "gen.js"},
        {title: "Sủng", input: BASE_URL + "/truyen-sung/danh-sach/", script: "gen.js"},
        {title: "Thám Hiểm", input: BASE_URL + "/truyen-tham-hiem/danh-sach/", script: "gen.js"},
        {title: "Thương Nghiệp", input: BASE_URL + "/truyen-thuong-nghiep/danh-sach/", script: "gen.js"},
        {title: "Tiên Hiệp Kỳ Duyên", input: BASE_URL + "/truyen-tien-hiep-ky-duyen/danh-sach/", script: "gen.js"},
        {title: "Tiểu thuyết", input: BASE_URL + "/truyen-tieu-thuyet/danh-sach/", script: "gen.js"},
        {title: "Tiểu Thuyết Khác", input: BASE_URL + "/truyen-tieu-thuyet-khac/danh-sach/", script: "gen.js"},
        {title: "Tiểu Thuyết Lãng Mạn", input: BASE_URL + "/truyen-18-plus/danh-sach/", script: "gen.js"},
        {title: "Tiểu Thuyết Phương Tây", input: BASE_URL + "/truyen-tieu-thuyet-phuong-tay/danh-sach/", script: "gen.js"},
        {title: "Trọng Sinh", input: BASE_URL + "/truyen-trong-sinh/danh-sach/", script: "gen.js"},
        {title: "Trùng Sinh", input: BASE_URL + "/truyen-trung-sinh/danh-sach/", script: "gen.js"},
        {title: "Truyện Ma", input: BASE_URL + "/truyen-truyen-ma/danh-sach/", script: "gen.js"},
        {title: "Truyện Ngắn", input: BASE_URL + "/truyen-truyen-ngan/danh-sach/", script: "gen.js"},
        {title: "Truyện Tây Phương", input: BASE_URL + "/truyen-truyen-tay-phuong/danh-sach/", script: "gen.js"},
        {title: "Truyện Teen", input: BASE_URL + "/truyen-truyen-teen/danh-sach/", script: "gen.js"},
        {title: "Truyện Tình Cảm", input: BASE_URL + "/truyen-truyen-tinh-cam/danh-sach/", script: "gen.js"},
        {title: "Văn Học Việt Nam", input: BASE_URL + "/truyen-van-hoc-viet-nam/danh-sach/", script: "gen.js"},
        {title: "Việt Nam", input: BASE_URL + "/truyen-viet-nam/danh-sach/", script: "gen.js"},
        {title: "Võ Hiệp", input: BASE_URL + "/truyen-vo-hiep/danh-sach/", script: "gen.js"},
        {title: "Võ Thuật", input: BASE_URL + "/truyen-vo-thuat/danh-sach/", script: "gen.js"},
        {title: "Xuyên Nhanh", input: BASE_URL + "/truyen-xuyen-nhanh/danh-sach/", script: "gen.js"}
    ]);
}