function execute() {
    return Response.success([
        {title: "Huyền Huyễn", input: "https://truyenyy.vip/truyen-huyen-huyen/danh-sach/", script: "gen.js"},
        {title: "Kiếm Hiệp", input: "https://truyenyy.vip/truyen-kiem-hiep/danh-sach/", script: "gen.js"},
        {title: "Lịch Sử", input: "https://truyenyy.vip/truyen-lich-su/danh-sach/", script: "gen.js"},
        {title: "Ngôn Tình", input: "https://truyenyy.vip/truyen-ngon-tinh/danh-sach/", script: "gen.js"},
        {title: "Sắc Hiệp", input: "https://truyenyy.vip/truyen-sac-hiep/danh-sach/", script: "gen.js"},
        {title: "Tiên Hiệp", input: "https://truyenyy.vip/truyen-tien-hiep/danh-sach/", script: "gen.js"},
        {title: "Dị Giới", input: "https://truyenyy.vip/truyen-di-gioi/danh-sach/", script: "gen.js"},
        {title: "Đô Thị", input: "https://truyenyy.vip/truyen-do-thi/danh-sach/", script: "gen.js"},
        {title: "Huyền Ảo", input: "https://truyenyy.vip/truyen-huyen-ao/danh-sach/", script: "gen.js"},
        {title: "Trinh Thám", input: "https://truyenyy.vip/truyen-trinh-tham/danh-sach/", script: "gen.js"},
        {title: "Cổ Đại", input: "https://truyenyy.vip/truyen-co-dai/danh-sach/", script: "gen.js"},
        {title: "Hệ Thống", input: "https://truyenyy.vip/truyen-he-thong/danh-sach/", script: "gen.js"},
        {title: "Khoa Huyễn", input: "https://truyenyy.vip/truyen-khoa-huyen/danh-sach/", script: "gen.js"},
        {title: "Quân Sự", input: "https://truyenyy.vip/truyen-quan-su/danh-sach/", script: "gen.js"},
        {title: "Võng Du", input: "https://truyenyy.vip/truyen-vong-du/danh-sach/", script: "gen.js"},
        {title: "Xuyên Không", input: "https://truyenyy.vip/truyen-xuyen-khong/danh-sach/", script: "gen.js"},
        {title: "Cổ Tiên Hiệp", input: "https://truyenyy.vip/truyen-co-tien-hiep/danh-sach/", script: "gen.js"},
        {title: "Đam Mỹ", input: "https://truyenyy.vip/truyen-dam-my/danh-sach/", script: "gen.js"},
        {title: "Huyền Bí", input: "https://truyenyy.vip/truyen-huyen-bi/danh-sach/", script: "gen.js"},
        {title: "Kỳ Huyễn", input: "https://truyenyy.vip/truyen-ky-huyen/danh-sach/", script: "gen.js"},
        {title: "Linh Dị", input: "https://truyenyy.vip/truyen-linh-di/danh-sach/", script: "gen.js"},
        {title: "Ma Pháp", input: "https://truyenyy.vip/truyen-huyen-huyen-ma-phap/danh-sach/", script: "gen.js"},
        {title: "Mạt Thế", input: "https://truyenyy.vip/truyen-mat-the/danh-sach/", script: "gen.js"},
        {title: "Quan Trường", input: "https://truyenyy.vip/truyen-quan-truong/danh-sach/", script: "gen.js"},
        {title: "Thể Thao", input: "https://truyenyy.vip/truyen-the-thao/danh-sach/", script: "gen.js"},
        {title: "Tu Chân", input: "https://truyenyy.vip/truyen-tu-chan-tieu-thuyet/danh-sach/", script: "gen.js"},
        {title: "Hiện Đại", input: "https://truyenyy.vip/truyen-hien-dai/danh-sach/", script: "gen.js"},
        {title: "Bách Hợp", input: "https://truyenyy.vip/truyen-bach-hop/danh-sach/", script: "gen.js"},
        {title: "Bình Đạm", input: "https://truyenyy.vip/truyen-binh-dam/danh-sach/", script: "gen.js"},
        {title: "Cạnh Kỹ", input: "https://truyenyy.vip/truyen-canh-ky/danh-sach/", script: "gen.js"},
        {title: "Cổ Đại Ngôn Tình", input: "https://truyenyy.vip/truyen-co-dai-ngon-tinh/danh-sach/", script: "gen.js"},
        {title: "Cung Đấu", input: "https://truyenyy.vip/truyen-cung-dau/danh-sach/", script: "gen.js"},
        {title: "Đặc Sắc", input: "https://truyenyy.vip/truyen-sac/danh-sach/", script: "gen.js"},
        {title: "Điền Văn", input: "https://truyenyy.vip/truyen-dien-van/danh-sach/", script: "gen.js"},
        {title: "Dị Năng", input: "https://truyenyy.vip/truyen-di-nang/danh-sach/", script: "gen.js"},
        {title: "Đoản Văn", input: "https://truyenyy.vip/truyen-doan-van/danh-sach/", script: "gen.js"},
        {title: "Đồng Nhân", input: "https://truyenyy.vip/truyen-dong-nhan/danh-sach/", script: "gen.js"},
        {title: "Đông Phương", input: "https://truyenyy.vip/truyen-dong-phuong/danh-sach/", script: "gen.js"},
        {title: "Gia Đấu", input: "https://truyenyy.vip/truyen-gia-dau/danh-sach/", script: "gen.js"},
        {title: "Hài Hước", input: "https://truyenyy.vip/truyen-hai-huoc/danh-sach/", script: "gen.js"},
        {title: "Hiện Đại Ngôn Tình", input: "https://truyenyy.vip/truyen-hien-dai-ngon-tinh/danh-sach/", script: "gen.js"},
        {title: "Hồng Hoang", input: "https://truyenyy.vip/truyen-hong-hoang/danh-sach/", script: "gen.js"},
        {title: "Huyền Huyễn Ngôn Tình", input: "https://truyenyy.vip/truyen-huyen-huyen-ngon-tinh/danh-sach/", script: "gen.js"},
        {title: "Huyền Nghi", input: "https://truyenyy.vip/truyen-huyen-nghi/danh-sach/", script: "gen.js"},
        {title: "Huyền Nghi Thần Quái", input: "https://truyenyy.vip/truyen-huyen-nghi-than-quai/danh-sach/", script: "gen.js"},
        {title: "Khác", input: "https://truyenyy.vip/truyen-khac/danh-sach/", script: "gen.js"},
        {title: "Khoa Huyễn Không Gian", input: "https://truyenyy.vip/truyen-khoa-huyen-khong-gian/danh-sach/", script: "gen.js"},
        {title: "Kỳ Ảo", input: "https://truyenyy.vip/truyen-ky-ao/danh-sach/", script: "gen.js"},
        {title: "Lãng Mạn Thanh Xuân", input: "https://truyenyy.vip/truyen-lang-man-thanh-xuan/danh-sach/", script: "gen.js"},
        {title: "Light Novel", input: "https://truyenyy.vip/truyen-light-novel/danh-sach/", script: "gen.js"},
        {title: "Ngược", input: "https://truyenyy.vip/truyen-nguoc/danh-sach/", script: "gen.js"},
        {title: "Nhàn Hưu", input: "https://truyenyy.vip/truyen-nhan-huu/danh-sach/", script: "gen.js"},
        {title: "Nhiều Converter", input: "https://truyenyy.vip/truyen-nhieu-converter/danh-sach/", script: "gen.js"},
        {title: "Nữ Cường", input: "https://truyenyy.vip/truyen-nu-cuong/danh-sach/", script: "gen.js"},
        {title: "Nữ Hiệp", input: "https://truyenyy.vip/truyen-nu-hiep/danh-sach/", script: "gen.js"},
        {title: "Nữ Phụ", input: "https://truyenyy.vip/truyen-nu-phu/danh-sach/", script: "gen.js"},
        {title: "Phiêu Lưu", input: "https://truyenyy.vip/truyen-phieu-luu/danh-sach/", script: "gen.js"},
        {title: "Phương Tây", input: "https://truyenyy.vip/truyen-phuong-tay/danh-sach/", script: "gen.js"},
        {title: "Sắc", input: "https://truyenyy.vip/truyen-sac-2/danh-sach/", script: "gen.js"},
        {title: "Sủng", input: "https://truyenyy.vip/truyen-sung/danh-sach/", script: "gen.js"},
        {title: "Thám Hiểm", input: "https://truyenyy.vip/truyen-tham-hiem/danh-sach/", script: "gen.js"},
        {title: "Thương Nghiệp", input: "https://truyenyy.vip/truyen-thuong-nghiep/danh-sach/", script: "gen.js"},
        {title: "Tiên Hiệp Kỳ Duyên", input: "https://truyenyy.vip/truyen-tien-hiep-ky-duyen/danh-sach/", script: "gen.js"},
        {title: "Tiểu thuyết", input: "https://truyenyy.vip/truyen-tieu-thuyet/danh-sach/", script: "gen.js"},
        {title: "Tiểu Thuyết Khác", input: "https://truyenyy.vip/truyen-tieu-thuyet-khac/danh-sach/", script: "gen.js"},
        {title: "Tiểu Thuyết Lãng Mạn", input: "https://truyenyy.vip/truyen-18-plus/danh-sach/", script: "gen.js"},
        {title: "Tiểu Thuyết Phương Tây", input: "https://truyenyy.vip/truyen-tieu-thuyet-phuong-tay/danh-sach/", script: "gen.js"},
        {title: "Trọng Sinh", input: "https://truyenyy.vip/truyen-trong-sinh/danh-sach/", script: "gen.js"},
        {title: "Trùng Sinh", input: "https://truyenyy.vip/truyen-trung-sinh/danh-sach/", script: "gen.js"},
        {title: "Truyện Ma", input: "https://truyenyy.vip/truyen-truyen-ma/danh-sach/", script: "gen.js"},
        {title: "Truyện Ngắn", input: "https://truyenyy.vip/truyen-truyen-ngan/danh-sach/", script: "gen.js"},
        {title: "Truyện Tây Phương", input: "https://truyenyy.vip/truyen-truyen-tay-phuong/danh-sach/", script: "gen.js"},
        {title: "Truyện Teen", input: "https://truyenyy.vip/truyen-truyen-teen/danh-sach/", script: "gen.js"},
        {title: "Truyện Tình Cảm", input: "https://truyenyy.vip/truyen-truyen-tinh-cam/danh-sach/", script: "gen.js"},
        {title: "Văn Học Việt Nam", input: "https://truyenyy.vip/truyen-van-hoc-viet-nam/danh-sach/", script: "gen.js"},
        {title: "Việt Nam", input: "https://truyenyy.vip/truyen-viet-nam/danh-sach/", script: "gen.js"},
        {title: "Võ Hiệp", input: "https://truyenyy.vip/truyen-vo-hiep/danh-sach/", script: "gen.js"},
        {title: "Võ Thuật", input: "https://truyenyy.vip/truyen-vo-thuat/danh-sach/", script: "gen.js"},
        {title: "Xuyên Nhanh", input: "https://truyenyy.vip/truyen-xuyen-nhanh/danh-sach/", script: "gen.js"}
    ]);
}