let voices = [
    {"id": "en_male_jomboy", "language": "en", "name": "Game On"},
    {"id": "en_us_002", "language": "en", "name": "Jessie"},
    {"id": "es_mx_002", "language": "en", "name": "Warm"},
    {"id": "en_male_funny", "language": "en", "name": "Wacky"},
    {"id": "en_us_ghostface", "language": "en", "name": "Scream"},
    {"id": "en_female_samc", "language": "en", "name": "Empathetic"},
    {"id": "en_male_cody", "language": "en", "name": "Serious"},
    {"id": "en_female_makeup", "language": "en", "name": "Beauty Guru"},
    {"id": "en_female_richgirl", "language": "en", "name": "Bestie"},
    {"id": "en_male_grinch", "language": "en", "name": "Trickster"},
    {"id": "en_us_006", "language": "en", "name": "Joey"},
    {"id": "en_male_narration", "language": "en", "name": "Story Teller"},
    {"id": "en_male_deadpool", "language": "en", "name": "Mr. GoodGuy"},
    {"id": "en_uk_001", "language": "en", "name": "Narrator"},
    {"id": "en_uk_003", "language": "en", "name": "Male English UK"},
    {"id": "en_au_001", "language": "en", "name": "Metro"},
    {"id": "en_male_jarvis", "language": "en", "name": "Alfred"},
    {"id": "en_male_ashmagic", "language": "en", "name": "ashmagic"},
    {"id": "en_male_olantekkers", "language": "en", "name": "olantekkers"},
    {"id": "en_male_ukneighbor", "language": "en", "name": "Lord Cringe"},
    {"id": "en_male_ukbutler", "language": "en", "name": "Mr. Meticulous"},
    {"id": "en_female_shenna", "language": "en", "name": "Debutante"},
    {"id": "en_female_pansino", "language": "en", "name": "Varsity"},
    {"id": "en_male_trevor", "language": "en", "name": "Marty"},
    {"id": "en_female_f08_twinkle", "language": "en", "name": "Pop Lullaby"},
    {"id": "en_male_m03_classical", "language": "en", "name": "Classic Electric"},
    {"id": "en_female_betty", "language": "en", "name": "Bae"},
    {"id": "en_male_cupid", "language": "en", "name": "Cupid"},
    {"id": "en_female_grandma", "language": "en", "name": "Granny"},
    {"id": "en_male_m2_xhxs_m03_christmas", "language": "en", "name": "Cozy"},
    {"id": "en_male_santa_narration", "language": "en", "name": "Author"},
    {"id": "en_male_sing_deep_jingle", "language": "en", "name": "Caroler"},
    {"id": "en_male_santa_effect", "language": "en", "name": "Santa"},
    {"id": "en_female_ht_f08_newyear", "language": "en", "name": "NYE 2023"},
    {"id": "en_male_wizard", "language": "en", "name": "Magician"},
    {"id": "en_female_ht_f08_halloween", "language": "en", "name": "Opera"},
    {"id": "en_female_ht_f08_glorious", "language": "en", "name": "Euphoric"},
    {"id": "en_male_sing_funny_it_goes_up", "language": "en", "name": "Hypetrain"},
    {"id": "en_female_ht_f08_wonderful_world", "language": "en", "name": "Melodrama"},
    {"id": "en_male_m2_xhxs_m03_silly", "language": "en", "name": "Quirky Time"},
    {"id": "en_female_emotional", "language": "en", "name": "Peaceful"},
    {"id": "en_male_m03_sunshine_soon", "language": "en", "name": "Toon Beat"},
    {"id": "en_female_f08_warmy_breeze", "language": "en", "name": "Open Mic"},
    {"id": "en_male_m03_lobby", "language": "en", "name": "Jingle"},
    {"id": "en_male_sing_funny_thanksgiving", "language": "en", "name": "Thanksgiving"},
    {"id": "en_female_f08_salut_damour", "language": "en", "name": "Cottagecore"},
    {"id": "en_us_007", "language": "en", "name": "Professor"},
    {"id": "en_us_009", "language": "en", "name": "Scientist"},
    {"id": "en_us_010", "language": "en", "name": "Confidence"},
    {"id": "en_au_002", "language": "en", "name": "Smooth"},
    {"id": "en_us_ghostface", "language": "en", "name": "Ghost Face"},
    {"id": "en_us_chewbacca", "language": "en", "name": "Chewbacca"},
    {"id": "en_us_c3po", "language": "en", "name": "C3PO"},
    {"id": "en_us_stitch", "language": "en", "name": "Stitch"},
    {"id": "en_us_stormtrooper", "language": "en", "name": "Stormtrooper"},
    {"id": "en_us_rocket", "language": "en", "name": "Rocket"},
    {"id": "en_female_madam_leota", "language": "en", "name": "Madame Leota"},
    {"id": "en_male_ghosthost", "language": "en", "name": "Ghost Host"},
    {"id": "en_male_pirate", "language": "en", "name": "Pirate"},
    {"id": "fr_001", "language": "fr", "name": "French - Male 1"},
    {"id": "fr_002", "language": "fr", "name": "French - Male 2"},
    {"id": "es_002", "language": "es", "name": "Spanish (Spain) - Male"},
    {"id": "es_mx_002", "language": "es", "name": "Spanish MX - Male"},
    {"id": "br_001", "language": "br", "name": "Portuguese BR - Female 1"},
    {"id": "br_003", "language": "br", "name": "Portuguese BR - Female 2"},
    {"id": "br_004", "language": "br", "name": "Portuguese BR - Female 3"},
    {"id": "br_005", "language": "br", "name": "Portuguese BR - Male"},
    {"id": "bp_female_ludmilla", "language": "br", "name": "Ludmilla"},
    {"id": "pt_female_lhays", "language": "pt", "name": "Lhays Macedo"},
    {"id": "pt_female_laizza", "language": "pt", "name": "Laizza"},
    {"id": "de_001", "language": "de", "name": "German - Female"},
    {"id": "de_002", "language": "de", "name": "German - Male"},
    {"id": "id_001", "language": "id", "name": "Female"},
    {"id": "jp_001", "language": "ja", "name": "Japanese - Female 1"},
    {"id": "jp_003", "language": "ja", "name": "Japanese - Female 2"},
    {"id": "jp_005", "language": "ja", "name": "Japanese - Female 3"},
    {"id": "jp_006", "language": "ja", "name": "Japanese - Male"},
    {"id": "jp_female_fujicochan", "language": "ja", "name": "りーさ"},
    {"id": "jp_female_hasegawariona", "language": "ja", "name": "世羅鈴"},
    {"id": "jp_male_keiichinakano", "language": "ja", "name": "Morio’s Kitchen"},
    {"id": "jp_female_oomaeaika", "language": "ja", "name": "夏絵ココ"},
    {"id": "jp_male_yujinchigusa", "language": "ja", "name": "低音ボイス"},
    {"id": "jp_female_shirou", "language": "ja", "name": "四郎"},
    {"id": "jp_male_tamawakazuki", "language": "ja", "name": "玉川寿紀"},
    {"id": "jp_female_kaorishoji", "language": "ja", "name": "庄司果織"},
    {"id": "jp_female_yagishaki", "language": "ja", "name": "八木沙季"},
    {"id": "jp_male_hikakin", "language": "ja", "name": "ヒカキン"},
    {"id": "jp_female_rei", "language": "ja", "name": "丸山礼"},
    {"id": "jp_male_shuichiro", "language": "ja", "name": "修一朗"},
    {"id": "jp_male_matsudake", "language": "ja", "name": "マツダ家の日常"},
    {"id": "jp_female_machikoriiita", "language": "ja", "name": "まちこりーた"},
    {"id": "jp_male_matsuo", "language": "ja", "name": "モジャオ"},
    {"id": "jp_male_osada", "language": "ja", "name": "モリスケ"},
    {"id": "kr_002", "language": "kr", "name": "Korean - Male 1"},
    {"id": "kr_003", "language": "kr", "name": "Korean - Female"},
    {"id": "kr_004", "language": "kr", "name": "Korean - Male 2"},
    {"id": "BV074_streaming", "language": "vi", "name": "Cô Gái Hoạt Ngôn"},
    {"id": "BV075_streaming", "language": "vi", "name": "Thanh Niên Tự Tin"},
    {"id": "vi_female_huong", "language": "vi", "name": "Giọng Nữ Phổ Thông"},
    {"id": "BV421_vivn_streaming", "language": "vi", "name": "Nguồn Nhỏ Ngọt Ngào"},
    {"id": "BV560_streaming", "language": "vi", "name": "Anh Dũng"},
    {"id": "BV562_streaming", "language": "vi", "name": "Chí Mai"},
    {"id": "en_female_f08_salut_damour", "language": "en", "name": "Alto"},
    {"id": "en_male_m03_lobby", "language": "en", "name": "Tenor"},
    {"id": "en_male_m03_sunshine_soon", "language": "en", "name": "Sunshine Soon"},
    {"id": "en_female_f08_warmy_breeze", "language": "en", "name": "Warmy Breeze"},
    {"id": "en_female_ht_f08_glorious", "language": "en", "name": "Glorious"},
    {"id": "en_male_sing_funny_it_goes_up", "language": "en", "name": "It Goes Up"},
    {"id": "en_male_m2_xhxs_m03_silly", "language": "en", "name": "Chipmunk"},
    {"id": "en_female_ht_f08_wonderful_world", "language": "en", "name": "Dramatic"}
];