function execute() {
    return Response.success([
        {title: "Comedy", input: "https://qmanga.net/danh-muc/comedy", script: "gen.js"},
        {title: "Historical", input: "https://qmanga.net/danh-muc/historical", script: "gen.js"},
        {title: "Manhua", input: "https://qmanga.net/danh-muc/manhua", script: "gen.js"},
        {title: "Mystery", input: "https://qmanga.net/danh-muc/mystery", script: "gen.js"},
        {title: "Ngôn Tình", input: "https://qmanga.net/danh-muc/ngon-tinh", script: "gen.js"},
        {title: "Romance", input: "https://qmanga.net/danh-muc/romance", script: "gen.js"},
        {title: "Shoujo", input: "https://qmanga.net/danh-muc/shoujo", script: "gen.js"},
        {title: "Truyện Màu", input: "https://qmanga.net/danh-muc/truyen-mau", script: "gen.js"},
        {title: "Fantasy", input: "https://qmanga.net/danh-muc/fantasy", script: "gen.js"},
        {title: "Supernatural", input: "https://qmanga.net/danh-muc/supernatural", script: "gen.js"},
        {title: "School Life", input: "https://qmanga.net/danh-muc/school-life", script: "gen.js"},
        {title: "Slice of life", input: "https://qmanga.net/danh-muc/slice-of-life", script: "gen.js"},
        {title: "Drama", input: "https://qmanga.net/danh-muc/drama", script: "gen.js"},
        {title: "Action", input: "https://qmanga.net/danh-muc/action", script: "gen.js"},
        {title: "Adventure", input: "https://qmanga.net/danh-muc/adventure", script: "gen.js"},
        {title: "Martial Arts", input: "https://qmanga.net/danh-muc/martial-arts", script: "gen.js"},
        {title: "One Shot", input: "https://qmanga.net/danh-muc/one-shot", script: "gen.js"},
        {title: "Sci-fi", input: "https://qmanga.net/danh-muc/sci-fi", script: "gen.js"},
        {title: "Shounen", input: "https://qmanga.net/danh-muc/shounen", script: "gen.js"},
        {title: "Ecchi", input: "https://qmanga.net/danh-muc/ecchi", script: "gen.js"},
        {title: "Trưởng thành 18+", input: "https://qmanga.net/danh-muc/truong-thanh-18", script: "gen.js"},
        {title: "Horror", input: "https://qmanga.net/danh-muc/horror", script: "gen.js"},
        {title: "Adult", input: "https://qmanga.net/danh-muc/adult", script: "gen.js"},
        {title: "Shounen Ai", input: "https://qmanga.net/danh-muc/shounen-ai", script: "gen.js"},
        {title: "Truyện Hàn (Manhwa)", input: "https://qmanga.net/danh-muc/truyen-han-manhwa", script: "gen.js"},
        {title: "Webtoon", input: "https://qmanga.net/danh-muc/webtoon", script: "gen.js"},
        {title: "Harem", input: "https://qmanga.net/danh-muc/harem", script: "gen.js"},
        {title: "Isekai", input: "https://qmanga.net/danh-muc/isekai", script: "gen.js"},
        {title: "Truyện Tàu (Manhua)", input: "https://qmanga.net/danh-muc/truyen-tau-manhua", script: "gen.js"},
        {title: "Yaoi", input: "https://qmanga.net/danh-muc/yaoi", script: "gen.js"},
        {title: "Truyện Nhật (Manga)", input: "https://qmanga.net/danh-muc/truyen-nhat-manga", script: "gen.js"},
        {title: "Doujinshi", input: "https://qmanga.net/danh-muc/doujinshi", script: "gen.js"},
        {title: "Yuri", input: "https://qmanga.net/danh-muc/yuri", script: "gen.js"},
        {title: "Smut", input: "https://qmanga.net/danh-muc/smut", script: "gen.js"},
        {title: "Chuyển sinh", input: "https://qmanga.net/danh-muc/chuyen-sinh", script: "gen.js"},
        {title: "Trưởng thành 17+", input: "https://qmanga.net/danh-muc/truong-thanh-17", script: "gen.js"},
        {title: "Seinen", input: "https://qmanga.net/danh-muc/seinen", script: "gen.js"},
        {title: "Sports", input: "https://qmanga.net/danh-muc/sports", script: "gen.js"},
        {title: "manga", input: "https://qmanga.net/danh-muc/manga", script: "gen.js"},
        {title: "Manhwa", input: "https://qmanga.net/danh-muc/manhwa", script: "gen.js"},
        {title: "Truyền Việt", input: "https://qmanga.net/danh-muc/truyen-viet", script: "gen.js"},
        {title: "Mecha", input: "https://qmanga.net/danh-muc/mecha", script: "gen.js"},
        {title: "Comic", input: "https://qmanga.net/danh-muc/comic", script: "gen.js"},
        {title: "Soft Yuri", input: "https://qmanga.net/danh-muc/soft-yuri", script: "gen.js"},
        {title: "Trinh Thám", input: "https://qmanga.net/danh-muc/trinh-tham", script: "gen.js"},
        {title: "Xuyên Không", input: "https://qmanga.net/danh-muc/xuyen-khong", script: "gen.js"},
        {title: "Soft Yaoi", input: "https://qmanga.net/danh-muc/soft-yaoi", script: "gen.js"},
        {title: "Cổ Đại", input: "https://qmanga.net/danh-muc/co-dai", script: "gen.js"},
        {title: "Anime", input: "https://qmanga.net/danh-muc/anime", script: "gen.js"},
        {title: "Psychological", input: "https://qmanga.net/danh-muc/psychological", script: "gen.js"},
        {title: "NTR", input: "https://qmanga.net/danh-muc/ntr", script: "gen.js"},
        {title: "Mature", input: "https://qmanga.net/danh-muc/mature", script: "gen.js"},
        {title: "Tạp chí truyện tranh", input: "https://qmanga.net/danh-muc/tap-chi-truyen-tranh", script: "gen.js"},
        {title: "Đam Mỹ", input: "https://qmanga.net/danh-muc/dam-my", script: "gen.js"},
        {title: "Detective", input: "https://qmanga.net/danh-muc/detective", script: "gen.js"},
        {title: "BL Manhwa", input: "https://qmanga.net/danh-muc/bl-manhwa", script: "gen.js"},
        {title: "BL Manhua", input: "https://qmanga.net/danh-muc/bl-manhua", script: "gen.js"},
        {title: "Magic", input: "https://qmanga.net/danh-muc/magic", script: "gen.js"},
        {title: "Full màu", input: "https://qmanga.net/danh-muc/full-mau", script: "gen.js"},
        {title: "Boy Love", input: "https://qmanga.net/danh-muc/boy-love", script: "gen.js"},
        {title: "Live action", input: "https://qmanga.net/danh-muc/live-action", script: "gen.js"},
        {title: "Truyện scan", input: "https://qmanga.net/danh-muc/truyen-scan", script: "gen.js"},
        {title: "18+", input: "https://qmanga.net/danh-muc/18", script: "gen.js"},
        {title: "Việt Nam", input: "https://qmanga.net/danh-muc/viet-nam", script: "gen.js"},
        {title: "Trọng Sinh", input: "https://qmanga.net/danh-muc/trong-sinh", script: "gen.js"},
        {title: "Huyền Huyễn", input: "https://qmanga.net/danh-muc/huyen-huyen", script: "gen.js"},
        {title: "Music", input: "https://qmanga.net/danh-muc/music", script: "gen.js"},
        {title: "Tu chân - tu tiên", input: "https://qmanga.net/danh-muc/tu-chan-tu-tien", script: "gen.js"},
        {title: "Game", input: "https://qmanga.net/danh-muc/game", script: "gen.js"},
        {title: "Thiếu Nhi", input: "https://qmanga.net/danh-muc/thieu-nhi", script: "gen.js"},
        {title: "S&amp;M", input: "https://qmanga.net/danh-muc/sm", script: "gen.js"},
        {title: "ABO", input: "https://qmanga.net/danh-muc/abo", script: "gen.js"}
    ]);
}