local genre = {}
table.insert(genre, { ["title"] = "Ngôn Tình", ["input"] = "https://thichdoctruyen.com/the-loai/ngon-tinh", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Kiếm hiệp", ["input"] = "https://thichdoctruyen.com/the-loai/kiem-hiep", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Tiên hiệp", ["input"] = "https://thichdoctruyen.com/the-loai/tien-hiep", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Sắc Hiệp", ["input"] = "https://thichdoctruyen.com/the-loai/sac-hiep", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Xuyên Không", ["input"] = "https://thichdoctruyen.com/the-loai/xuyen-khong", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Truyện Teen", ["input"] = "https://thichdoctruyen.com/the-loai/truyen-teen", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Lịch sử", ["input"] = "https://thichdoctruyen.com/the-loai/lich-su", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Quân sự", ["input"] = "https://thichdoctruyen.com/the-loai/quan-su", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Đô thị", ["input"] = "https://thichdoctruyen.com/the-loai/do-thi", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Võng Du", ["input"] = "https://thichdoctruyen.com/the-loai/vong-du", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Dị Năng", ["input"] = "https://thichdoctruyen.com/the-loai/di-nang", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Khoa Huyễn", ["input"] = "https://thichdoctruyen.com/the-loai/khoa-huyen", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Trinh thám", ["input"] = "https://thichdoctruyen.com/the-loai/trinh-tham", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Truyện ma", ["input"] = "https://thichdoctruyen.com/the-loai/truyen-ma", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Truyện Ngắn", ["input"] = "https://thichdoctruyen.com/the-loai/truyen-ngan", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Huyền Huyễn", ["input"] = "https://thichdoctruyen.com/the-loai/huyen-huyen", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Dị Giới", ["input"] = "https://thichdoctruyen.com/the-loai/di-gioi", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Nữ cường", ["input"] = "https://thichdoctruyen.com/danh-muc/nu-cuong", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Nam cường", ["input"] = "https://thichdoctruyen.com/danh-muc/nam-cuong", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Trùng sinh", ["input"] = "https://thichdoctruyen.com/danh-muc/trung-sinh", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Nữ phụ", ["input"] = "https://thichdoctruyen.com/danh-muc/nu-phu", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Phản xuyên", ["input"] = "https://thichdoctruyen.com/danh-muc/phan-xuyen", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Nữ tôn", ["input"] = "https://thichdoctruyen.com/danh-muc/nu-ton", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Đam Mỹ", ["input"] = "https://thichdoctruyen.com/danh-muc/dam-my", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Bách hợp", ["input"] = "https://thichdoctruyen.com/danh-muc/bach-hop", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Mạt thế", ["input"] = "https://thichdoctruyen.com/danh-muc/mat-the", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Đông Phương", ["input"] = "https://thichdoctruyen.com/danh-muc/dong-phuong", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Điền Văn", ["input"] = "https://thichdoctruyen.com/danh-muc/dien-van", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Cổ Đại", ["input"] = "https://thichdoctruyen.com/danh-muc/co-dai", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Gia Đấu", ["input"] = "https://thichdoctruyen.com/danh-muc/gia-dau", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Cung Đấu", ["input"] = "https://thichdoctruyen.com/danh-muc/cung-dau", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Linh Dị", ["input"] = "https://thichdoctruyen.com/danh-muc/linh-di", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Trọng Sinh", ["input"] = "https://thichdoctruyen.com/danh-muc/trong-sinh", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Thám Hiểm", ["input"] = "https://thichdoctruyen.com/danh-muc/tham-hiem", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Quan Trường", ["input"] = "https://thichdoctruyen.com/danh-muc/quan-truong", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Giang Hồ", ["input"] = "https://thichdoctruyen.com/danh-muc/giang-ho", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Truyện Sủng", ["input"] = "https://thichdoctruyen.com/danh-muc/truyen-sung", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Truyện Ngược", ["input"] = "https://thichdoctruyen.com/danh-muc/truyen-nguoc", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Viễn Tưởng", ["input"] = "https://thichdoctruyen.com/danh-muc/vien-tuong", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Xuất Bản", ["input"] = "https://thichdoctruyen.com/danh-muc/xuat-ban", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Hắc Bang", ["input"] = "https://thichdoctruyen.com/danh-muc/hac-bang", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Quân Nhân", ["input"] = "https://thichdoctruyen.com/danh-muc/quan-nhan", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Phương Tây ", ["input"] = "https://thichdoctruyen.com/danh-muc/phuong-tay", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Truyện Sắc", ["input"] = "https://thichdoctruyen.com/danh-muc/truyen-sac", ["script"] = "gen.lua" })
table.insert(genre, { ["title"] = "Khác", ["input"] = "https://thichdoctruyen.com/danh-muc/khac", ["script"] = "gen.lua" })
return response:success(genre)