function execute() {
    return Response.success([
        {title: "Ngôn Tình", input: "https://thichdoctruyen.vip/the-loai/ngon-tinh", script: "gen.js"},
        {title: "Kiếm hiệp", input: "https://thichdoctruyen.vip/the-loai/kiem-hiep", script: "gen.js"},
        {title: "Tiên hiệp", input: "https://thichdoctruyen.vip/the-loai/tien-hiep", script: "gen.js"},
        {title: "Sắc Hiệp", input: "https://thichdoctruyen.vip/the-loai/sac-hiep", script: "gen.js"},
        {title: "Xuyên Không", input: "https://thichdoctruyen.vip/the-loai/xuyen-khong", script: "gen.js"},
        {title: "Truyện Teen", input: "https://thichdoctruyen.vip/the-loai/truyen-teen", script: "gen.js"},
        {title: "Lịch sử", input: "https://thichdoctruyen.vip/the-loai/lich-su", script: "gen.js"},
        {title: "Quân sự", input: "https://thichdoctruyen.vip/the-loai/quan-su", script: "gen.js"},
        {title: "Đô thị", input: "https://thichdoctruyen.vip/the-loai/do-thi", script: "gen.js"},
        {title: "Võng Du", input: "https://thichdoctruyen.vip/the-loai/vong-du", script: "gen.js"},
        {title: "Dị Năng", input: "https://thichdoctruyen.vip/the-loai/di-nang", script: "gen.js"},
        {title: "Khoa Huyễn", input: "https://thichdoctruyen.vip/the-loai/khoa-huyen", script: "gen.js"},
        {title: "Trinh thám", input: "https://thichdoctruyen.vip/the-loai/trinh-tham", script: "gen.js"},
        {title: "Truyện ma", input: "https://thichdoctruyen.vip/the-loai/truyen-ma", script: "gen.js"},
        {title: "Truyện Ngắn", input: "https://thichdoctruyen.vip/the-loai/truyen-ngan", script: "gen.js"},
        {title: "Huyền Huyễn", input: "https://thichdoctruyen.vip/the-loai/huyen-huyen", script: "gen.js"},
        {title: "Dị Giới", input: "https://thichdoctruyen.vip/the-loai/di-gioi", script: "gen.js"},
        {title: "Nữ cường", input: "https://thichdoctruyen.vip/danh-muc/nu-cuong", script: "gen.js"},
        {title: "Nam cường", input: "https://thichdoctruyen.vip/danh-muc/nam-cuong", script: "gen.js"},
        {title: "Trùng sinh", input: "https://thichdoctruyen.vip/danh-muc/trung-sinh", script: "gen.js"},
        {title: "Nữ phụ", input: "https://thichdoctruyen.vip/danh-muc/nu-phu", script: "gen.js"},
        {title: "Phản xuyên", input: "https://thichdoctruyen.vip/danh-muc/phan-xuyen", script: "gen.js"},
        {title: "Nữ tôn", input: "https://thichdoctruyen.vip/danh-muc/nu-ton", script: "gen.js"},
        {title: "Đam Mỹ", input: "https://thichdoctruyen.vip/danh-muc/dam-my", script: "gen.js"},
        {title: "Bách hợp", input: "https://thichdoctruyen.vip/danh-muc/bach-hop", script: "gen.js"},
        {title: "Mạt thế", input: "https://thichdoctruyen.vip/danh-muc/mat-the", script: "gen.js"},
        {title: "Đông Phương", input: "https://thichdoctruyen.vip/danh-muc/dong-phuong", script: "gen.js"},
        {title: "Điền Văn", input: "https://thichdoctruyen.vip/danh-muc/dien-van", script: "gen.js"},
        {title: "Cổ Đại", input: "https://thichdoctruyen.vip/danh-muc/co-dai", script: "gen.js"},
        {title: "Gia Đấu", input: "https://thichdoctruyen.vip/danh-muc/gia-dau", script: "gen.js"},
        {title: "Cung Đấu", input: "https://thichdoctruyen.vip/danh-muc/cung-dau", script: "gen.js"},
        {title: "Linh Dị", input: "https://thichdoctruyen.vip/danh-muc/linh-di", script: "gen.js"},
        {title: "Trọng Sinh", input: "https://thichdoctruyen.vip/danh-muc/trong-sinh", script: "gen.js"},
        {title: "Thám Hiểm", input: "https://thichdoctruyen.vip/danh-muc/tham-hiem", script: "gen.js"},
        {title: "Quan Trường", input: "https://thichdoctruyen.vip/danh-muc/quan-truong", script: "gen.js"},
        {title: "Giang Hồ", input: "https://thichdoctruyen.vip/danh-muc/giang-ho", script: "gen.js"},
        {title: "Truyện Sủng", input: "https://thichdoctruyen.vip/danh-muc/truyen-sung", script: "gen.js"},
        {title: "Truyện Ngược", input: "https://thichdoctruyen.vip/danh-muc/truyen-nguoc", script: "gen.js"},
        {title: "Viễn Tưởng", input: "https://thichdoctruyen.vip/danh-muc/vien-tuong", script: "gen.js"},
        {title: "Xuất Bản", input: "https://thichdoctruyen.vip/danh-muc/xuat-ban", script: "gen.js"},
        {title: "Hắc Bang", input: "https://thichdoctruyen.vip/danh-muc/hac-bang", script: "gen.js"},
        {title: "Quân Nhân", input: "https://thichdoctruyen.vip/danh-muc/quan-nhan", script: "gen.js"},
        {title: "Phương Tây", input: "https://thichdoctruyen.vip/danh-muc/phuong-tay", script: "gen.js"},
        {title: "Truyện Sắc", input: "https://thichdoctruyen.vip/danh-muc/truyen-sac", script: "gen.js"},
        {title: "Khác", input: "https://thichdoctruyen.vip/danh-muc/khac", script: "gen.js"}
    ]);
}