function execute() {
    return Response.success([
        { title: "1v1", input: "https://truyencuatui.net/the-loai/1v1.html", script: "gen.js"},
        { title: "ABO", input: "https://truyencuatui.net/the-loai/abo.html", script: "gen.js"},
        { title: "Bách Hợp", input: "https://truyencuatui.net/the-loai/bach-hop.html", script: "gen.js"},
        { title: "Báo thù", input: "https://truyencuatui.net/the-loai/bao-thu.html", script: "gen.js"},
        { title: "Biến thành động vật", input: "https://truyencuatui.net/the-loai/bien-thanh-dong-vat.html", script: "gen.js"},
        { title: "Cận đại", input: "https://truyencuatui.net/the-loai/can-dai.html", script: "gen.js"},
        { title: "Cạnh Kỹ", input: "https://truyencuatui.net/the-loai/canh-ky.html", script: "gen.js"},
        { title: "Chủ công", input: "https://truyencuatui.net/the-loai/chu-cong.html", script: "gen.js"},
        { title: "Chủ thụ", input: "https://truyencuatui.net/the-loai/chu-thu.html", script: "gen.js"},
        { title: "Cổ Đại", input: "https://truyencuatui.net/the-loai/co-dai.html", script: "gen.js"},
        { title: "Cơ giáp", input: "https://truyencuatui.net/the-loai/co-giap.html", script: "gen.js"},
        { title: "Cổ Trang", input: "https://truyencuatui.net/the-loai/co-trang.html", script: "gen.js"},
        { title: "Convert", input: "https://truyencuatui.net/the-loai/convert.html", script: "gen.js"},
        { title: "Cung Đấu", input: "https://truyencuatui.net/the-loai/cung-dau.html", script: "gen.js"},
        { title: "Cung đình hầu tước", input: "https://truyencuatui.net/the-loai/cung-dinh-hau-tuoc.html", script: "gen.js"},
        { title: "Cường cường", input: "https://truyencuatui.net/the-loai/cuong-cuong.html", script: "gen.js"},
        { title: "Dã Sử", input: "https://truyencuatui.net/the-loai/da-su.html", script: "gen.js"},
        { title: "Đam Mỹ", input: "https://truyencuatui.net/the-loai/dam-my.html", script: "gen.js"},
        { title: "Dị Giới", input: "https://truyencuatui.net/the-loai/di-gioi.html", script: "gen.js"},
        { title: "Dị Năng", input: "https://truyencuatui.net/the-loai/di-nang.html", script: "gen.js"},
        { title: "Dị thế", input: "https://truyencuatui.net/the-loai/di-the.html", script: "gen.js"},
        { title: "Diễn sinh", input: "https://truyencuatui.net/the-loai/dien-sinh.html", script: "gen.js"},
        { title: "Điền Văn", input: "https://truyencuatui.net/the-loai/dien-van.html", script: "gen.js"},
        { title: "Đô Thị", input: "https://truyencuatui.net/the-loai/do-thi.html", script: "gen.js"},
        { title: "Đô thị tình duyên", input: "https://truyencuatui.net/the-loai/do-thi-tinh-duyen.html", script: "gen.js"},
        { title: "Đoản Văn", input: "https://truyencuatui.net/the-loai/doan-van.html", script: "gen.js"},
        { title: "Đồng Nhân", input: "https://truyencuatui.net/the-loai/dong-nhan.html", script: "gen.js"},
        { title: "Đông Phương", input: "https://truyencuatui.net/the-loai/dong-phuong.html", script: "gen.js"},
        { title: "Du Hí", input: "https://truyencuatui.net/the-loai/du-hi.html", script: "gen.js"},
        { title: "Dưỡng thành", input: "https://truyencuatui.net/the-loai/duong-thanh.html", script: "gen.js"},
        { title: "Duyên trời tác hợp", input: "https://truyencuatui.net/the-loai/duyen-troi-tac-hop.html", script: "gen.js"},
        { title: "Gia Đấu", input: "https://truyencuatui.net/the-loai/gia-dau.html", script: "gen.js"},
        { title: "Giả Tưởng", input: "https://truyencuatui.net/the-loai/gia-tuong.html", script: "gen.js"},
        { title: "Giới giải trí", input: "https://truyencuatui.net/the-loai/gioi-giai-tri.html", script: "gen.js"},
        { title: "Hắc Bang", input: "https://truyencuatui.net/the-loai/hac-bang.html", script: "gen.js"},
        { title: "Hài Hước", input: "https://truyencuatui.net/the-loai/hai-huoc.html", script: "gen.js"},
        { title: "Hào môn thế gia", input: "https://truyencuatui.net/the-loai/hao-mon-the-gia.html", script: "gen.js"},
        { title: "Harem", input: "https://truyencuatui.net/the-loai/harem.html", script: "gen.js"},
        { title: "HE", input: "https://truyencuatui.net/the-loai/he.html", script: "gen.js"},
        { title: "Hệ thống", input: "https://truyencuatui.net/the-loai/he-thong.html", script: "gen.js"},
        { title: "Hiện Đại", input: "https://truyencuatui.net/the-loai/hien-dai.html", script: "gen.js"},
        { title: "Hồng Hoang", input: "https://truyencuatui.net/the-loai/hong-hoang.html", script: "gen.js"},
        { title: "Hồng Lâu", input: "https://truyencuatui.net/the-loai/hong-lau.html", script: "gen.js"},
        { title: "Hương Thổ", input: "https://truyencuatui.net/the-loai/huong-tho.html", script: "gen.js"},
        { title: "Huyền Ảo", input: "https://truyencuatui.net/the-loai/huyen-ao.html", script: "gen.js"},
        { title: "Huyền Bí", input: "https://truyencuatui.net/the-loai/huyen-bi.html", script: "gen.js"},
        { title: "Huyền Bí - Giả Tưởng", input: "https://truyencuatui.net/the-loai/huyen-bi-gia-tuong.html", script: "gen.js"},
        { title: "Huyền Huyễn", input: "https://truyencuatui.net/the-loai/huyen-huyen.html", script: "gen.js"},
        { title: "Khác", input: "https://truyencuatui.net/the-loai/khac.html", script: "gen.js"},
        { title: "Khoa Ảo", input: "https://truyencuatui.net/the-loai/khoa-ao.html", script: "gen.js"},
        { title: "Khoa học viễn tưởng", input: "https://truyencuatui.net/the-loai/khoa-hoc-vien-tuong.html", script: "gen.js"},
        { title: "Khoa Huyễn", input: "https://truyencuatui.net/the-loai/khoa-huyen.html", script: "gen.js"},
        { title: "Không CP", input: "https://truyencuatui.net/the-loai/khong-cp.html", script: "gen.js"},
        { title: "Kiếm Hiệp", input: "https://truyencuatui.net/the-loai/kiem-hiep.html", script: "gen.js"},
        { title: "Kim bài đề cử ", input: "https://truyencuatui.net/the-loai/kim-bai-de-cu.html", script: "gen.js"},
        { title: "Kinh Dị", input: "https://truyencuatui.net/the-loai/kinh-di.html", script: "gen.js"},
        { title: "Kỳ Huyễn", input: "https://truyencuatui.net/the-loai/ky-huyen.html", script: "gen.js"},
        { title: "Làm giàu", input: "https://truyencuatui.net/the-loai/lam-giau.html", script: "gen.js"},
        { title: "Làm ruộng", input: "https://truyencuatui.net/the-loai/lam-ruong.html", script: "gen.js"},
        { title: "Lãng Mạn", input: "https://truyencuatui.net/the-loai/lang-man.html", script: "gen.js"},
        { title: "Lịch Sử", input: "https://truyencuatui.net/the-loai/lich-su.html", script: "gen.js"},
        { title: "Light Novel", input: "https://truyencuatui.net/the-loai/light-novel.html", script: "gen.js"},
        { title: "Linh Dị", input: "https://truyencuatui.net/the-loai/linh-di.html", script: "gen.js"},
        { title: "Linh dị thần quái", input: "https://truyencuatui.net/the-loai/linh-di-than-quai.html", script: "gen.js"},
        { title: "Mãn Thanh", input: "https://truyencuatui.net/the-loai/man-thanh.html", script: "gen.js"},
        { title: "Mạt Thế", input: "https://truyencuatui.net/the-loai/mat-the.html", script: "gen.js"},
        { title: "Mỹ thực", input: "https://truyencuatui.net/the-loai/my-thuc.html", script: "gen.js"},
        { title: "Nam sinh", input: "https://truyencuatui.net/the-loai/nam-sinh.html", script: "gen.js"},
        { title: "Ngân bài đề cử ", input: "https://truyencuatui.net/the-loai/ngan-bai-de-cu.html", script: "gen.js"},
        { title: "Nghịch tập", input: "https://truyencuatui.net/the-loai/nghich-tap.html", script: "gen.js"},
        { title: "Ngôn Tình", input: "https://truyencuatui.net/the-loai/ngon-tinh.html", script: "gen.js"},
        { title: "Ngọt sủng", input: "https://truyencuatui.net/the-loai/ngot-sung.html", script: "gen.js"},
        { title: "Ngược", input: "https://truyencuatui.net/the-loai/nguoc.html", script: "gen.js"},
        { title: "Ngược Tâm", input: "https://truyencuatui.net/the-loai/nguoc-tam.html", script: "gen.js"},
        { title: "Ngược tra", input: "https://truyencuatui.net/the-loai/nguoc-tra.html", script: "gen.js"},
        { title: "Nguyên sang", input: "https://truyencuatui.net/the-loai/nguyen-sang.html", script: "gen.js"},
        { title: "Nguyên thủy", input: "https://truyencuatui.net/the-loai/nguyen-thuy.html", script: "gen.js"},
        { title: "Nhân sinh", input: "https://truyencuatui.net/the-loai/nhan-sinh.html", script: "gen.js"},
        { title: "Nhân Thú", input: "https://truyencuatui.net/the-loai/nhan-thu.html", script: "gen.js"},
        { title: "Nhật Ký", input: "https://truyencuatui.net/the-loai/nhat-ky.html", script: "gen.js"},
        { title: "Nhẹ nhàng", input: "https://truyencuatui.net/the-loai/nhe-nhang.html", script: "gen.js"},
        { title: "Niên hạ", input: "https://truyencuatui.net/the-loai/nien-ha.html", script: "gen.js"},
        { title: "Nữ Cường", input: "https://truyencuatui.net/the-loai/nu-cuong.html", script: "gen.js"},
        { title: "Nữ Hiệp", input: "https://truyencuatui.net/the-loai/nu-hiep.html", script: "gen.js"},
        { title: "Nữ Phụ", input: "https://truyencuatui.net/the-loai/nu-phu.html", script: "gen.js"},
        { title: "Nữ tôn", input: "https://truyencuatui.net/the-loai/nu-ton.html", script: "gen.js"},
        { title: "OE", input: "https://truyencuatui.net/the-loai/oe.html", script: "gen.js"},
        { title: "Phá án", input: "https://truyencuatui.net/the-loai/pha-an.html", script: "gen.js"},
        { title: "Pháo hôi", input: "https://truyencuatui.net/the-loai/phao-hoi.html", script: "gen.js"},
        { title: "Phát sóng trực tiếp", input: "https://truyencuatui.net/the-loai/phat-song-truc-tiep.html", script: "gen.js"},
        { title: "Phiêu Lưu", input: "https://truyencuatui.net/the-loai/phieu-luu.html", script: "gen.js"},
        { title: "Phong thủy", input: "https://truyencuatui.net/the-loai/phong-thuy.html", script: "gen.js"},
        { title: "Phương Tây", input: "https://truyencuatui.net/the-loai/phuong-tay.html", script: "gen.js"},
        { title: "Quân Nhân", input: "https://truyencuatui.net/the-loai/quan-nhan.html", script: "gen.js"},
        { title: "Quân Sự", input: "https://truyencuatui.net/the-loai/quan-su.html", script: "gen.js"},
        { title: "Quan Trường", input: "https://truyencuatui.net/the-loai/quan-truong.html", script: "gen.js"},
        { title: "Sắc", input: "https://truyencuatui.net/the-loai/sac.html", script: "gen.js"},
        { title: "Sắc Hiệp", input: "https://truyencuatui.net/the-loai/sac-hiep.html", script: "gen.js"},
        { title: "Sảng văn", input: "https://truyencuatui.net/the-loai/sang-van.html", script: "gen.js"},
        { title: "Sát Thủ", input: "https://truyencuatui.net/the-loai/sat-thu.html", script: "gen.js"},
        { title: "SE", input: "https://truyencuatui.net/the-loai/se.html", script: "gen.js"},
        { title: "Song khiết", input: "https://truyencuatui.net/the-loai/song-khiet.html", script: "gen.js"},
        { title: "Sủng", input: "https://truyencuatui.net/the-loai/sung.html", script: "gen.js"},
        { title: "Tâm Lý Xã Hội", input: "https://truyencuatui.net/the-loai/tam-ly-xa-hoi.html", script: "gen.js"},
        { title: "Thám Hiểm", input: "https://truyencuatui.net/the-loai/tham-hiem.html", script: "gen.js"},
        { title: "Thần tiên yêu quái", input: "https://truyencuatui.net/the-loai/than-tien-yeu-quai.html", script: "gen.js"},
        { title: "thanh thủy văn", input: "https://truyencuatui.net/the-loai/thanh-thuy-van.html", script: "gen.js"},
        { title: "Thiên chi kiêu tử", input: "https://truyencuatui.net/the-loai/thien-chi-kieu-tu.html", script: "gen.js"},
        { title: "Thư", input: "https://truyencuatui.net/the-loai/thu.html", script: "gen.js"},
        { title: "Thú nhân", input: "https://truyencuatui.net/the-loai/thu-nhan.html", script: "gen.js"},
        { title: "Thương chiến", input: "https://truyencuatui.net/the-loai/thuong-chien.html", script: "gen.js"},
        { title: "Tiên Hiệp", input: "https://truyencuatui.net/the-loai/tien-hiep.html", script: "gen.js"},
        { title: "Tiểu Thuyết", input: "https://truyencuatui.net/the-loai/tieu-thuyet.html", script: "gen.js"},
        { title: "Tiểu Thuyết Phương Tây", input: "https://truyencuatui.net/the-loai/tieu-thuyet-phuong-tay.html", script: "gen.js"},
        { title: "Tình Cảm", input: "https://truyencuatui.net/the-loai/tinh-cam.html", script: "gen.js"},
        { title: "Tinh tế", input: "https://truyencuatui.net/the-loai/tinh-te.html", script: "gen.js"},
        { title: "Trạch đấu", input: "https://truyencuatui.net/the-loai/trach-dau.html", script: "gen.js"},
        { title: "Triết lý", input: "https://truyencuatui.net/the-loai/triet-ly.html", script: "gen.js"},
        { title: "Trinh Thám", input: "https://truyencuatui.net/the-loai/trinh-tham.html", script: "gen.js"},
        { title: "Trò chơi", input: "https://truyencuatui.net/the-loai/tro-choi.html", script: "gen.js"},
        { title: "Trọng Sinh", input: "https://truyencuatui.net/the-loai/trong-sinh.html", script: "gen.js"},
        { title: "Truyện Dài", input: "https://truyencuatui.net/the-loai/truyen-dai.html", script: "gen.js"},
        { title: "Truyện Hay", input: "https://truyencuatui.net/the-loai/truyen-hay.html", script: "gen.js"},
        { title: "Truyện Ma", input: "https://truyencuatui.net/the-loai/truyen-ma.html", script: "gen.js"},
        { title: "Truyện Ngắn", input: "https://truyencuatui.net/the-loai/truyen-ngan.html", script: "gen.js"},
        { title: "Truyện ngắn hài Nhật Bản", input: "https://truyencuatui.net/the-loai/truyen-ngan-hai-nhat-ban.html", script: "gen.js"},
        { title: "Truyện Teen", input: "https://truyencuatui.net/the-loai/truyen-teen.html", script: "gen.js"},
        { title: "Truyện Tranh", input: "https://truyencuatui.net/the-loai/truyen-tranh.html", script: "gen.js"},
        { title: "Truyện Việt", input: "https://truyencuatui.net/the-loai/truyen-viet.html", script: "gen.js"},
        { title: "Tu chân", input: "https://truyencuatui.net/the-loai/tu-chan.html", script: "gen.js"},
        { title: "Tuổi Học Trò", input: "https://truyencuatui.net/the-loai/tuoi-hoc-tro.html", script: "gen.js"},
        { title: "Tương Lai", input: "https://truyencuatui.net/the-loai/tuong-lai.html", script: "gen.js"},
        { title: "Tùy thân không gian", input: "https://truyencuatui.net/the-loai/tuy-than-khong-gian.html", script: "gen.js"},
        { title: "Văn học", input: "https://truyencuatui.net/the-loai/van-hoc.html", script: "gen.js"},
        { title: "Văn học Cổ điển", input: "https://truyencuatui.net/the-loai/van-hoc-co-dien.html", script: "gen.js"},
        { title: "Văn Học", input: "https://truyencuatui.net/the-loai/van-hoc-nuoc-ngoai.html", script: "gen.js"},
        { title: "Văn học Phương Tây", input: "https://truyencuatui.net/the-loai/van-hoc-phuong-tay.html", script: "gen.js"},
        { title: "Văn học Việt", input: "https://truyencuatui.net/the-loai/van-hoc-viet.html", script: "gen.js"},
        { title: "Văn học Việt Nam", input: "https://truyencuatui.net/the-loai/van-hoc-viet-nam.html", script: "gen.js"},
        { title: "Viễn Tưởng", input: "https://truyencuatui.net/the-loai/vien-tuong.html", script: "gen.js"},
        { title: "Việt Nam", input: "https://truyencuatui.net/the-loai/viet-nam.html", script: "gen.js"},
        { title: "Vô Hạn Lưu", input: "https://truyencuatui.net/the-loai/vo-han-luu.html", script: "gen.js"},
        { title: "Võ Hiệp", input: "https://truyencuatui.net/the-loai/vo-hiep.html", script: "gen.js"},
        { title: "Võng Du", input: "https://truyencuatui.net/the-loai/vong-du.html", script: "gen.js"},
        { title: "Võng hồng", input: "https://truyencuatui.net/the-loai/vong-hong.html", script: "gen.js"},
        { title: "Web Novel", input: "https://truyencuatui.net/the-loai/web-novel.html", script: "gen.js"},
        { title: "Xuyên Không", input: "https://truyencuatui.net/the-loai/xuyen-khong.html", script: "gen.js"},
        { title: "Xuyên nhanh", input: "https://truyencuatui.net/the-loai/xuyen-nhanh.html", script: "gen.js"},
        { title: "Xuyên sách", input: "https://truyencuatui.net/the-loai/xuyen-sach.html", script: "gen.js"},
        { title: "Xuyên việt", input: "https://truyencuatui.net/the-loai/xuyen-viet.html", script: "gen.js"}
    ]);
}