function execute() {
    return Response.success([
        {title: "Action", input: "https://lightnovelreader.org/category/action", script: "gen.js"},
        {title: "Adventure", input: "https://lightnovelreader.org/category/adventure", script: "gen.js"},
        {title: "Boys Love", input: "https://lightnovelreader.org/category/boys-love", script: "gen.js"},
        {title: "Celebrity", input: "https://lightnovelreader.org/category/celebrity", script: "gen.js"},
        {title: "Comedy", input: "https://lightnovelreader.org/category/comedy", script: "gen.js"},
        {title: "Dark Fantasy", input: "https://lightnovelreader.org/category/dark-fantasy", script: "gen.js"},
        {title: "Drama", input: "https://lightnovelreader.org/category/drama", script: "gen.js"},
        {title: "Ecchi", input: "https://lightnovelreader.org/category/ecchi", script: "gen.js"},
        {title: "Fantasy", input: "https://lightnovelreader.org/category/fantasy", script: "gen.js"},
        {title: "Gender Bender", input: "https://lightnovelreader.org/category/gender-bender", script: "gen.js"},
        {title: "Harem", input: "https://lightnovelreader.org/category/harem", script: "gen.js"},
        {title: "Historical", input: "https://lightnovelreader.org/category/historical", script: "gen.js"},
        {title: "Horror", input: "https://lightnovelreader.org/category/horror", script: "gen.js"},
        {title: "Isekai", input: "https://lightnovelreader.org/category/isekai", script: "gen.js"},
        {title: "Josei", input: "https://lightnovelreader.org/category/josei", script: "gen.js"},
        {title: "LitRPG", input: "https://lightnovelreader.org/category/litrpg", script: "gen.js"},
        {title: "Martial Arts", input: "https://lightnovelreader.org/category/martial-arts", script: "gen.js"},
        {title: "Mature", input: "https://lightnovelreader.org/category/mature", script: "gen.js"},
        {title: "Mecha", input: "https://lightnovelreader.org/category/mecha", script: "gen.js"},
        {title: "Mystery", input: "https://lightnovelreader.org/category/mystery", script: "gen.js"},
        {title: "Psychological", input: "https://lightnovelreader.org/category/psychological", script: "gen.js"},
        {title: "Romance", input: "https://lightnovelreader.org/category/romance", script: "gen.js"},
        {title: "School Life", input: "https://lightnovelreader.org/category/school-life", script: "gen.js"},
        {title: "Sci-fi", input: "https://lightnovelreader.org/category/sci-fi", script: "gen.js"},
        {title: "Seinen", input: "https://lightnovelreader.org/category/seinen", script: "gen.js"},
        {title: "Shotacon", input: "https://lightnovelreader.org/category/shotacon", script: "gen.js"},
        {title: "Shoujo", input: "https://lightnovelreader.org/category/shoujo", script: "gen.js"},
        {title: "Shoujo Ai", input: "https://lightnovelreader.org/category/shoujo-ai", script: "gen.js"},
        {title: "Shounen", input: "https://lightnovelreader.org/category/shounen", script: "gen.js"},
        {title: "Shounen Ai", input: "https://lightnovelreader.org/category/shounen-ai", script: "gen.js"},
        {title: "Slice of Life", input: "https://lightnovelreader.org/category/slice-of-life", script: "gen.js"},
        {title: "Smut", input: "https://lightnovelreader.org/category/smut", script: "gen.js"},
        {title: "Sports", input: "https://lightnovelreader.org/category/sports", script: "gen.js"},
        {title: "Supernatural", input: "https://lightnovelreader.org/category/supernatural", script: "gen.js"},
        {title: "Tragedy", input: "https://lightnovelreader.org/category/tragedy", script: "gen.js"},
        {title: "Wuxia", input: "https://lightnovelreader.org/category/wuxia", script: "gen.js"},
        {title: "Xianxia", input: "https://lightnovelreader.org/category/xianxia", script: "gen.js"},
        {title: "Xuanhuan", input: "https://lightnovelreader.org/category/xuanhuan", script: "gen.js"},
        {title: "Yaoi", input: "https://lightnovelreader.org/category/yaoi", script: "gen.js"},
        {title: "Yuri", input: "https://lightnovelreader.org/category/yuri", script: "gen.js"}
    ]);
}