function execute() {
    return Response.success([
        {title: "Action", input: "/category/action", script: "gen.js"},
        {title: "Adventure", input: "/category/adventure", script: "gen.js"},
        {title: "Boys Love", input: "/category/boys-love", script: "gen.js"},
        {title: "Celebrity", input: "/category/celebrity", script: "gen.js"},
        {title: "Comedy", input: "/category/comedy", script: "gen.js"},
        {title: "Dark Fantasy", input: "/category/dark-fantasy", script: "gen.js"},
        {title: "Drama", input: "/category/drama", script: "gen.js"},
        {title: "Ecchi", input: "/category/ecchi", script: "gen.js"},
        {title: "Fantasy", input: "/category/fantasy", script: "gen.js"},
        {title: "Gender Bender", input: "/category/gender-bender", script: "gen.js"},
        {title: "Harem", input: "/category/harem", script: "gen.js"},
        {title: "Historical", input: "/category/historical", script: "gen.js"},
        {title: "Horror", input: "/category/horror", script: "gen.js"},
        {title: "Isekai", input: "/category/isekai", script: "gen.js"},
        {title: "Josei", input: "/category/josei", script: "gen.js"},
        {title: "LitRPG", input: "/category/litrpg", script: "gen.js"},
        {title: "Martial Arts", input: "/category/martial-arts", script: "gen.js"},
        {title: "Mature", input: "/category/mature", script: "gen.js"},
        {title: "Mecha", input: "/category/mecha", script: "gen.js"},
        {title: "Mystery", input: "/category/mystery", script: "gen.js"},
        {title: "Psychological", input: "/category/psychological", script: "gen.js"},
        {title: "Romance", input: "/category/romance", script: "gen.js"},
        {title: "School Life", input: "/category/school-life", script: "gen.js"},
        {title: "Sci-fi", input: "/category/sci-fi", script: "gen.js"},
        {title: "Seinen", input: "/category/seinen", script: "gen.js"},
        {title: "Shotacon", input: "/category/shotacon", script: "gen.js"},
        {title: "Shoujo", input: "/category/shoujo", script: "gen.js"},
        {title: "Shoujo Ai", input: "/category/shoujo-ai", script: "gen.js"},
        {title: "Shounen", input: "/category/shounen", script: "gen.js"},
        {title: "Shounen Ai", input: "/category/shounen-ai", script: "gen.js"},
        {title: "Slice of Life", input: "/category/slice-of-life", script: "gen.js"},
        {title: "Smut", input: "/category/smut", script: "gen.js"},
        {title: "Sports", input: "/category/sports", script: "gen.js"},
        {title: "Supernatural", input: "/category/supernatural", script: "gen.js"},
        {title: "Tragedy", input: "/category/tragedy", script: "gen.js"},
        {title: "Wuxia", input: "/category/wuxia", script: "gen.js"},
        {title: "Xianxia", input: "/category/xianxia", script: "gen.js"},
        {title: "Xuanhuan", input: "/category/xuanhuan", script: "gen.js"},
        {title: "Yaoi", input: "/category/yaoi", script: "gen.js"},
        {title: "Yuri", input: "/category/yuri", script: "gen.js"}
    ]);
}