let languages = [
    {"id": "zh"},
    {"id": "en"},
    {"id": "es"},
    {"id": "hi"},
    {"id": "ar"},
    {"id": "bn"},
    {"id": "pt"},
    {"id": "ru"},
    {"id": "ja"},
    {"id": "pa"},
    {"id": "de"},
    {"id": "jv"},
    {"id": "ko"},
    {"id": "fr"},
    {"id": "vi"},
    {"id": "te"},
    {"id": "tr"},
    {"id": "th"},
    {"id": "it"},
    {"id": "nl"},
    {"id": "fa"},
    {"id": "ms"},
    {"id": "sw"},
    {"id": "tl"}
]

const languageMap = {
    "zh": "zh",
    "en": "en",
    "es": "spa",
    "hi": "hi",
    "ar": "ara",
    "bn": "ben",
    "pt": "pt",
    "ru": "ru",
    "ja": "jp",
    "pa": "pan",
    "de": "de",
    "jv": "jav",
    "ko": "kor",
    "fr": "fra",
    "vi": "vie",
    "te": "tel",
    "tr": "tr",
    "th": "th",
    "it": "it",
    "nl": "nl",
    "fa": "per",
    "ms": "may",
    "sw": "swa",
    "tl": "fil"
}