function execute() {
    return Response.success([
        { title: "Ngôn tình", input: "/the-loai/ngon-tinh", script: "gen.js" },
        { title: "Truyện Teen", input: "/the-loai/truyen-teen", script: "gen.js" },
        { title: "Tiên Hiệp", input: "/the-loai/tien-hiep", script: "gen.js" },
        { title: "Kiếm Hiệp", input: "/the-loai/kiem-hiep", script: "gen.js" },
        { title: "Hiện đại", input: "/the-loai/hien-dai", script: "gen.js" },
        { title: "Đô Thị", input: "/the-loai/do-thi", script: "gen.js" },
        { title: "Cổ Đại", input: "/the-loai/co-dai", script: "gen.js" },
        { title: "Xuyên Không", input: "/the-loai/xuyen-khong", script: "gen.js" },
        { title: "Trọng Sinh", input: "/the-loai/trong-sinh", script: "gen.js" },
        { title: "Sắc", input: "/the-loai/sac", script: "gen.js" },
        { title: "Ngược", input: "/the-loai/nguoc", script: "gen.js" },
        { title: "Ngọt", input: "/the-loai/ngot", script: "gen.js" },
        { title: "Sủng", input: "/the-loai/sung", script: "gen.js" },
        { title: "Hài Hước", input: "/the-loai/hai-huoc", script: "gen.js" },
        { title: "Đam Mỹ", input: "/the-loai/dam-my", script: "gen.js" },
        { title: "Bách Hợp", input: "/the-loai/bach-hop", script: "gen.js" },
        { title: "Nữ Cường", input: "/the-loai/nu-cuong", script: "gen.js" },
        { title: "Nữ Phụ", input: "/the-loai/nu-phu", script: "gen.js" },
        { title: "Học Đường", input: "/the-loai/hoc-duong", script: "gen.js" },
        { title: "Quan Trường", input: "/the-loai/quan-truong", script: "gen.js" },
        { title: "Quân nhân", input: "/the-loai/quan-nhan", script: "gen.js" },
        { title: "Gia Đấu", input: "/the-loai/gia-dau", script: "gen.js" },
        { title: "Cung Đấu", input: "/the-loai/cung-dau", script: "gen.js" },
        { title: "Điền Văn", input: "/the-loai/dien-van", script: "gen.js" },
        { title: "Võng Du", input: "/the-loai/vong-du", script: "gen.js" },
        { title: "Huyền Huyễn", input: "/the-loai/huyen-huyen", script: "gen.js" },
        { title: "Dị Giới", input: "/the-loai/di-gioi", script: "gen.js" },
        { title: "Mạt Thế", input: "/the-loai/mat-the", script: "gen.js" },
        { title: "Truyện ngắn", input: "/the-loai/truyen-ngan", script: "gen.js" },
        { title: "Truyện ma - kinh dị", input: "/the-loai/truyen-ma-kinh-di", script: "gen.js" }
    ]);
}